### ISSUE TITLE
Investigate whether .item or .tolist can return a shapely-wrapped object

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#10]

**Comment by caspervdw** [comment]
@jorisvandenbossche  I vaguely remember that we can't do this. Do you know?

**Comment by jorisvandenbossche** [comment]
We don't control what numpy does with item/tolist (for that we would need to have a custom dtype, and the conclusion was that this is right now not possible), and since geometries are already just python objects for numpy, item/tolist will simply returns those geometries.

**Comment by caspervdw** [comment]
OK, so I’ll close this then
