### ISSUE TITLE
Doc build is failing

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#105]
From the readthedocs log I get the following:

```
 conda env create --quiet --name latest --file docs/environment.yml
Collecting package metadata (repodata.json): ...working... Killed


Command killed due to excessive memory consumption 
```

**Comment by jorisvandenbossche** [comment]
Yeah, that's a general problem with using conda on readthedocs .. (the conda solving step is taking too much memory). We regularly run into this with geopandas as well. A partial solution is pinning the versions more in the environment.yaml file (so pinning geos to eg 3.8.0, and adding a pinned version of numpy)
