### ISSUE TITLE
Document that from_shapely requires exactly the same GEOS library for both shapely and pygeos to function without potential errors

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#122]
Given a watershed - should be simple polygon
(shapefile: [bad_poly.zip](https://github.com/pygeos/pygeos/files/4370849/bad_poly.zip))

Read in via geopandas 0.7 (`df`) and converted to pygeos:

```
>>> geometry = pygeos.from_shapely(df.geometry)
```

Geopandas / shapely claim it is valid:
```
>>> df.geometry.is_valid
0    True
```

Pygeos raises exception:
```
>>> pygeos.is_valid(geometry)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bcward/projects/pygeos/pygeos/predicates.py", line 258, in is_valid
    result = lib.is_valid(geometry, **kwargs)
pygeos.GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
```

But otherwise pygeos thinks it is OK:
```
>>> pygeos.is_valid_input(geometry)
array([ True])
>>> pygeos.is_geometry(geometry)
array([ True])
```

If we round-trip the geometry through WKT or WKB, then it is valid and raises no exception:
```
>>> pygeos.is_valid(pygeos.from_wkt(pygeos.to_wkt(geometry)))
array([ True])
>>> pygeos.is_valid(pygeos.from_wkb(pygeos.to_wkb(geometry)))
array([ True])
```

Likewise, if I use WKT or WKB to go between the shapely geometry and pygeos, no errors:
```
>>> pg.is_valid(pg.from_wkt(df.geometry.apply(lambda g: g.to_wkt())))
0    True
Name: geometry, dtype: bool
>>> pg.is_valid(pg.from_wkb(df.geometry.apply(lambda g: g.to_wkb())))
array([ True])
```

I think there is a couple things going on here:
1) `pygeos::is_valid` should probably return `False` in this case rather than raise an exception.  It should handle exceptions from GEOS as indicating `False`.

2) there is a difference in behavior between `from_shapely` versus `from_wkt` / `from_wkb`.  It could be that that latter correct some underlying issue in the raw geometry that is passed through as-is via `from_shapely`.

**Comment by jorisvandenbossche** [comment]
This might be a GEOS version issue / build issue. I get 

```
In [48]: df = geopandas.read_file("zip://./../Downloads/bad_poly.zip")                                                                                                                                             

In [49]: geometry = pygeos.from_shapely(df.geometry)                                                                                                                                                               

In [50]: pygeos.is_valid(geometry)                                                                                                                                                                                 
Out[50]: array([ True])
```

with GEOS 3.8.0 in my development environment.

**Comment by brendan-ward** [comment]
I have GEOS 3.8.0 for both:
```
>>> pygeos.geos_version
(3, 8, 0)
>>> shapely.geos.geos_version
(3, 8, 0)
```

For this project, I installed geopandas / shapely via `pip` (within a `pyenv` / `pipenv` environment) whereas `pygeos` is using my local clone and built with `conda`.

I wonder if this is a case where the versions are the same but the underlying GEOS binaries are different?  Not sure why that would cause the conversion to be mostly successful but fail certain operations.

**Comment by jorisvandenbossche** [comment]
I created a conda env with geos=3.8.0 and pygeos, and then pip installed GeoPandas and Shapely in it, and getting the same result as I showed above. So can't reproduce it in that way either.

**Comment by brendan-ward** [comment]
@jorisvandenbossche thanks for looking into this!

Sorry for the lack of clarity about my environments.  There are two different environments getting spliced together on my end.

I have pygeos clone setup with conda (conda is via pyenv).

I have a different pipenv environment for this specific project with the above file.  In that environment, I have installed geopandas / shapely via pip.  I pulled in pygeos via `pip install -e ../pygeos` (they're siblings on the path) to leverage things on master there (merged now, so not likely as relevant).  pygeos is using system GEOS; I think shapely is using bundled GEOS.


In this environment (pipenv, not pygeos conda), I uninstalled geopandas, shapely, and pygeos.  I reinstalled (via pipenv) latest geopandas and `pygeos==0.6.0` (0.7.x brings in GEOS 3.8.1).

In that environment, I can reproduce the above errors.

**Comment by caspervdw** [comment]
This might be an actual bug introduced in GEOS 3.8.1:

https://github.com/libgeos/geos/pull/256

Or it might be because of different binaries that are used in shapely and pygeos. We took a risk in https://github.com/pygeos/pygeos/pull/61 by only comparing the version (and not the actual GEOS library in use). 

It would be good to isolate the bug.

**Comment by jorisvandenbossche** [comment]
> We took a risk in #61 by only comparing the version (and not the actual GEOS library in use).

Yes, in any case, I would personally only recommend to use `from_shapely` if you are using conda and thus are sure to use the exact same GEOS library.

**Comment by brendan-ward** [comment]
Unless there is a way to check if the GEOS library is the same, it seems like the only action necessary here is to document that this function requires using _exactly_ the same GEOS library.

Changed the title to reflect this.

**Comment by jorisvandenbossche** [comment]
https://github.com/pygeos/pygeos/pull/312 addressd the to/from_shapely conversion in case you have different GEOS versions. 

But this issue is actually about the same version but different libraries? (eg two GEOS libraries included in the pygeos and shapely wheels) So not yet closeable?

**Comment by brendan-ward** [comment]
I can no longer reproduce this; the issue originally appeared to be about the same version but different binary libraries.

I installed GEOS 3.9.1 & pygeos from conda-forge and shapely 1.8a1 from pip (also bound to GEOS 3.9.1 but shipped with the wheel?).

Given `wkb` from the above polygon (read via pyogrio):

```
>>> import pygeos as pg
>>> from shapely.wkb import loads
>>> pg.is_valid(pg.from_shapely(loads(wkb)))
True
```

I tried switching the import order of shapely and pygeos, but it still worked properly.  Not sure if this was something that was resolved in GEOS?  (not the wkb issue, but rather about library binary compatibility)

**Comment by jorisvandenbossche** [comment]
>  Not sure if this was something that was resolved in GEOS? (not the wkb issue, but rather about library binary compatibility)

Not sure either, but given that Shapely and PyGEOS will soon be the same package, and I wouldn't care too much about it
