### ISSUE TITLE
Dropping python 3.5 support

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#125]
Following up on https://github.com/pygeos/pygeos/pull/116

We decided that we want to start following numpy's deprecation protocol at https://numpy.org/neps/nep-0029-deprecation_policy.html .

For the next release, we want to limit Python to >= 3.6 and numpy to >= 1.15
GEOS we leave to >= 3.5 until Ubuntu 16 is out of support (April 2021).

@jorisvandenbossche will check with shapely what their policy is

**Comment by jorisvandenbossche** [comment]
All good on using Python 3.6+ here -> https://github.com/Toblerity/Shapely/issues/886

**Comment by jorisvandenbossche** [comment]
In the meantime Python 3.5 support has been removed (#211), and we have

https://github.com/pygeos/pygeos/blob/b3ae3004ab7081f7927d33a0df1abfaf5dc57136/setup.py#L201

So closing this issue.
