### ISSUE TITLE
Functions in GEOS > 3.5.0 to implement

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#126]
From the GEOS changes at https://github.com/libgeos/geos/blob/master/NEWS

Could be exposed as new functions:
- [x] GEOSBuildArea
- [x] GEOSMakeValid
- [ ] GEOSPolygonize_valid
- [x] GEOSCoverageUnion
- [x] GEOSMinimumBoundingCircle
- [x] GEOSCoordSeq_isCCW
- [x] GEOSFrechetDistance
- [x] GEOSReverse --> #243 
- [ ] GEOSSegmentIntersection
- [x] GEOSGeomGetZ
- [ ] GEOSGeom_{get,set}UserData (Rashad Kanavath)
- [x] GEOSGeom_{set,get}Precision (#257)
- [x] GEOSMinimumRotatedRectangle
- [ ] GEOSMaximumInscribedCircle
- [ ] GEOSLargestEmptyCircle
- [ ] GEOSMinimumWidth
- [x] GEOSMinimumClearance
- [ ] GEOSMinimumClearanceLine
- [x] GEOSDistanceWithin —> #417 
- [x] GEOSDensify —> #299 
- [ ] GEOSMakeValidWithParams
- [ ] GEOSWKBWriter_getFlavor, GEOSWKBWriter_setFlavor
- [ ] GEOSConstrainedDelaunayTriangulation

Having to do with strtree:
- [x] GEOSSTRtree_nearest  --> #111 
- [ ] GEOSDistanceIndexed

Functions that we could use internally:
- [ ] GEOSCoordSeq_setXY, GEOSCoordSeq_setXYZ, GEOSCoordSeq_getXY, GEOSCoordSeq_getXYZ
- [ ] GEOSGeom_createPointFromXY
- [ ] GEOSGeom_getXMin, GEOSGeom_getXMax, GEOSGeom_getYMin, GEOSGeom_getYMax 
- [x] GEOSCoordSeq_copyFromArrays, GEOSCoordSeq_copyFromBuffer,  GEOSCoordSeq_copyToArrays, GEOSCoordSeq_copyToBuffer

**Comment by brendan-ward** [comment]
Crossref: `GEOSSTRtree_nearest` is in #111 with related WIP by @adriangb.

@caspervdw is there a priority order to the above?
