### ISSUE TITLE
Function to "flatten" or "explode" multi-geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#127]
For several use cases in geopandas (the explode method, for plotting), it would be useful to have a function that explodes multi-geometries. 

In pseudo-python (and only for an array with only multi-geometries, would of course this needs to be generalized, but for illustration purposes), this could look like:

```
def flatten_multipolygons(arr):
   indices = [] 
   res = [] 
  
   for i, geom in enumerate(arr): 
        for j in range(pygeos.get_num_geometries(geom)): 
            poly = pygeos.get_geometry(geom, j) 
            res.append(poly)
            indices.append(i)
    
   return np.array(res, dtype=object), np.array(indices)
```

(the indices are already possible to calculate based on get_num_geometries(arr))

This is something that could be fairly easily implemented in cython, I think. Although we should check what performance benefit it can give. Thoughts?

Questions are *what* to explode though. MultiPoint/MultiLineString/MultiPolygon would be clear candidates, but GeometryCollection is maybe less clear (what with Multi geoms inside a GeometryCollection ?).

**Comment by brendan-ward** [comment]
Hah!  Just put together #128 at the exact same time!

Question: are we considering adding Cython in addition to doing everything in C?

It seems like we're touching on several cases where the API should return indices into the source in addition to other things.  STRtree::query_bulk was the first, and it probably had the most obvious spatial join pattern of left (source), right (tree).

For other cases like this, we should consider a consistent approach to the position of indices within the output (always first or always last).  This may need to generalize to cases of results of shape (3,n), e.g., in the case of nearest neighbors it could be source index, target index, distance

A `depth` parameter might be useful in the case of nested geometry collections.

I think exploding all the things 💥 seems like a reasonable default though.  I'm having a hard time thinking of a case where I would not want back all of the individual parts, regardless of the nesting.

**Comment by jorisvandenbossche** [comment]
What a coincidence! (or not, it needs to be useful functionality ;))

> Question: are we considering adding Cython in addition to doing everything in C?

See https://github.com/pygeos/pygeos/issues/51, let's try to decide on that there.

> I think exploding all the things boom seems like a reasonable default though. I'm having a hard time thinking of a case where I would not want back all of the individual parts, regardless of the nesting.

Yes, that probably makes sense.

I agree with your analysis in https://github.com/pygeos/pygeos/issues/128 that a function like this probably doesn't fit in the ufunc pattern, and I think we will typically want to limit this to 1D (otherwise the indices get a ragged array).
