### ISSUE TITLE
Support get/set_coordinates/apply with more than 2 dimensions

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#131]
Currently, the `apply` function (based on the `get_coordinates` / `set_coordinates` functions), explicitly states it is only for 2 dimensions and others will be dropped:

https://github.com/pygeos/pygeos/blob/b176e297c673671cd78f82738f1a899310501dd9/pygeos/coordinates.py#L7-L12

However, for using this function for coordinate transformations in GeoPandas, we need to be able to work with more than 2 dimensions (at least right now with Shapely, that is supported). 

@caspervdw do you remember if there was a fundamental reason this could not be done, or rather to keep the initial PR simpler?
 
I suppose the main problem is that there is no guarantee that all geometries in the array will have the same number of dimensions. 
However, I suppose there could be an option to specify how many dimensions should be used, and then in `get_coordinates`, those geometries that have less dimensions as the specified dimension can be filled with 0's or nan's for those missing dimensions?

**Comment by caspervdw** [comment]
There was certainly no fundamental reason that this could not be done, just a lot of work to get it right.

A preferable API would be `ndim=2` or `ndim=3`, determining how many 1D coordinate arrays are returned.
