### ISSUE TITLE
Missing modules in docs website?

### ISSUE THREAD

**Issue by kylebarron** [pygeos/pygeos#133]
It looks like there are a few modules in `pygeos/` that aren't in the public documentation website. Specifically I was looking for documentation on the creation methods in [`creation.py`](https://github.com/pygeos/pygeos/blob/master/pygeos/creation.py), but it's missing from the [Sphinx docs](https://pygeos.readthedocs.io/en/latest/index.html).

Is that intentional?

**Comment by jorisvandenbossche** [comment]
I don't think that is intentional. 
(the docs are not yet much developed, it's only the API docs right now)

**Comment by kylebarron** [comment]
Yes, but I meant that the API docs for some modules are missing. It looks like most of the existing documentation is auto generated from API docs, but `creation.py` doesn't have a page
