### ISSUE TITLE
Refactor GEOS_SINCE_3X0 to GEOS_SINCE_3_X_0

### ISSUE THREAD

**Issue by chaitan94** [pygeos/pygeos#143]
Probably `GEOS_SINCE_3_8_0` is a slightly better convention for these macros IMO, makes it a bit less ambiguous. Especially in the future, for say, in case of a 3.10.0 version.

https://github.com/pygeos/pygeos/blob/a999b767aecf409dfc8421314cbc6ee459dd9430/src/geos.h#L20

Should be a straight forward change, I can do a refactor and raise a PR for this if that works.

Let me know if you guys have any other ideas.

**Comment by caspervdw** [comment]
Good suggestion. Please go ahead!
