### ISSUE TITLE
pygeos.multilinestrings doesn't accept linearrings

### ISSUE THREAD

**Issue by abey79** [pygeos/pygeos#153]
`pygeos.multilinestrings` appears to reject input containing `LINEARRING`s. Is that on purpose? This differs from shapely's `MultiLineString()` behaviour.

**Comment by caspervdw** [comment]
Thanks for raising this issue @abey79  , I can confirm it is an actual bug; GEOS accepts LINEARRING for multilinestrings, so we should do it as well.
