### ISSUE TITLE
ENH: Consolidate repeated snippets used in ufuncs.c

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#165]
There are a few repeated snippets introduced in #156 that can be refactored into functions.

**Comment by caspervdw** [comment]
@brendan-ward I like the suggestion of the refactor, but I myself don't see enough benefit to actually do it.

Do you think you can make time for this?

**Comment by brendan-ward** [comment]
I think this is still a good idea over the long term, so I think we should keep this open.  In the short term, I don't have time to work on this.
