### ISSUE TITLE
ENH: add documentation / examples for using multiple threads with geometry-creating operations

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#166]
As introduced by #165, it would be good to add a few small examples of using multiple threads with geometry-creating operations, and reference use of multiple threads a bit more broadly in the documentation.

**Comment by caspervdw** [comment]
Partially addressed in #169 

Anyone has a good example?

**Comment by jorisvandenbossche** [comment]
When I test a GIL release change locally, lately I use this dask pattern for testing of ufuncs:

```
import pygeos

# array with pygeos geometries
arr =  pygeos.points(np.random.randn(100_000, 2))
point = pygeos.Geometry("POINT (0 0)")

# convert to chunked dask array
import dask.array
arr_dask = dask.array.from_array(arr, chunks=25_000)


res1 = pygeos.distance(arr, point)
res2 = arr_dask.map_blocks(pygeos.distance, point, dtype=float)
res2.compute()
```

You can probably do something similar with the built-in `threading` module or with a `ThreadPoolExecutor`, but I have found using dask to be easy to test wit when already working with arrays like this.

**Comment by caspervdw** [comment]
I wrote a blog about the new multithreading-compatibility of PyGEOS: 

https://caspervdw.github.io/Pygeos-Multithreading/
