### ISSUE TITLE
Finish release 0.8

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#172]
I like to get it out asap so people can start benefit from the GIL release (and other features)

Could you have a look at https://github.com/pygeos/pygeos/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.8 and comment on this?

**Comment by jorisvandenbossche** [comment]
Indeed, we should indeed try to release as soon as possible. 
WIth all GIL changes, I would personally still like to include https://github.com/pygeos/pygeos/pull/174 (GIL release for STRTree bulk query)

I think some of the older issues (eg https://github.com/pygeos/pygeos/issues/46 about pickling, https://github.com/pygeos/pygeos/issues/37 about skipping None in intersection_all) shouldn't be blockers for 0.8. It would certainly be nice to fix them, but they are not new issues or regressions.

**Comment by jorisvandenbossche** [comment]
Shall we try to release? 
I would like to still include #175 and #182, and maybe #179 is also nice. (but releases are cheap, so we should also "just" release and release more often if needed ;))

**Comment by caspervdw** [comment]
I like to have the segfault bugfix in https://github.com/pygeos/pygeos/pull/187 in still, after that :+1: to release 0.8!

**Comment by caspervdw** [comment]
@jorisvandenbossche  I think we can do the 0.8 release now. Shall I do it tomorrow?

**Comment by jorisvandenbossche** [comment]
Yes, that's fine!

**Comment by caspervdw** [comment]
Pygeos 0.8 is tagged on github and the sdist is on pypi.

Waiting for the following to build:
- https://github.com/pygeos/pygeos-wheels/pull/5
- https://github.com/conda-forge/pygeos-feedstock/pull/13

**Comment by caspervdw** [comment]
I merged the PRs, so the wheels / conda builds should become available in the next hour or so.

**Comment by jorisvandenbossche** [comment]
Thanks!
