### ISSUE TITLE
ENH: Add support for ContainsProperly predicate

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#180]
Note: this is exposed by GEOS only as an operation on prepared geometries.

**Comment by jorisvandenbossche** [comment]
> Note: this is exposed by GEOS only as an operation on prepared geometries.

It might be worth checking with GEOS why this is the case?

**Comment by brendan-ward** [comment]
It looks like this comes all the way from JTS:
* `containsProperly` in [`PreparedGeometry`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/prep/PreparedGeometry.html)
* `contains` but no `containsProperly` in [`Geometry`](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html)

Some of this is hinted by the comments in GEOS:
```
 * Uses short-circuit tests and indexing to improve performance.
 *
 * A Geometry A <tt>containsProperly</tt> another Geometry B iff
 * all points of B are contained in the Interior of A.
 * Equivalently, B is contained in A AND B does not intersect
 * the Boundary of A.
 *
 * The advantage to using this predicate is that it can be computed
 * efficiently, with no need to compute topology at individual points.
 * In a situation with many geometries intersecting the boundary
 * of the target geometry, this can make a performance difference.
```

**Comment by caspervdw** [comment]
This is closed by #157

**Comment by jorisvandenbossche** [comment]
The linked PR only added it to the STRtree, but I think the goal of the issue was to see if we can add it as a general predicate ufunc as well.

**Comment by brendan-ward** [comment]
Yes, the target here was to add to ufuncs, which is not done.
