### ISSUE TITLE
BUG: pygeos.constructive.snap snaps to incorrect point

### ISSUE THREAD

**Issue by rpgscience** [pygeos/pygeos#183]
Snap point is outside tolerance for some input geometries for v0.7.1. Reproduce using:

```
>>> a = pygeos.points([[512,174]])
>>> a
array([<pygeos.Geometry POINT (512 174)>], dtype=object)
>>> b = pygeos.polygons([[511, 195], [488, 191], [463, 181], [436, 181]])
>>> b
<pygeos.Geometry POLYGON ((511 195, 488 191, 463 181, 436 181, 511 195))>
>>> pygeos.snap(a, b, tolerance=30)
array([<pygeos.Geometry POINT (436 181)>], dtype=object)
```

**Comment by caspervdw** [comment]
Thanks for the report @rpgscience and sorry for my late reply. I can confirm the bug also with a MULTIPOINT:

```
>>> pygeos.snap(pygeos.Geometry("POINT (512 174)"), pygeos.Geometry("MULTIPOINT (511 195, 488 191, 463 181, 436 181)"), 30)                                              
<pygeos.Geometry POINT (436 181)
```

As pygeos does nothing more than wrapping `GEOSSnap_r` we can't really do anything about this. It should be reported at GEOS. See these tickets, maybe you can find something relevant there:

https://trac.osgeo.org/geos/ticket/544
https://trac.osgeo.org/geos/ticket/758
https://trac.osgeo.org/geos/ticket/760
