### ISSUE TITLE
PERF: Reintroduce a global GEOS context

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#192]
In #113, the global GEOS context was eliminated in favor of a context that was initialized and destroyed in every function. This was necessary for multithreading.

However, in https://github.com/pygeos/pygeos/pull/182, @jorisvandenbossche encountered a performance hit coming from this intialization/finalization of the context.

I am thinking especially of the *deallocation* of Geometry objects. It would probably be hard to time this, but I think that destroying a array with lots of geometries has taken a performance hit after #113. 

Maybe the functions that need the GIL anyway can benefit from keeping a global GEOS context around. I would like to explore this, and maybe we can also use a global WKB reader / writer and WKT reader / writer for speeding up single-geometry construction, and `repr` and `str` functions.

**Comment by jorisvandenbossche** [comment]
I suppose deallocation is one of the main cases where a method of the geometry gets called many times individually and where we don't have control to be able to call a vectorized function? (and pickling or hashing an array of geometries being other cases)

But indeed, also not directly an idea how to time this ..

The performance hit we saw for creation of simple points in https://github.com/pygeos/pygeos/pull/182 was a 50% slowdown. I suppose for deallocation it will be in a similar order of magnitude? Given that this is 50% for an operation that is generally cheap (compared to other ufuncs like overlays or buffers etc that create geometries), that is maybe acceptable? 

That said, functions needing the GIL could indeed use a global context as we had before. That doesn't sound as a huge complication to also keep a global one (and in principle the macro GEOS_INIT vs GEOS_INIT_THREADS could take care of assigning the global one or a newly initialized one to the `ctx` variable?)

**Comment by snowman2** [comment]
This may or may not be helpful, but pyproj allows users to toggle on using the global context at their own risk: https://pyproj4.github.io/pyproj/stable/api/global_context.html.

**Comment by jorisvandenbossche** [comment]
I opened an issue on the Shapely side to further track this over there: https://github.com/shapely/shapely/issues/1523
