### ISSUE TITLE
Default axis of union_all

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#194]
Currently the `union_all` function has a default to union over axis 0:

https://github.com/pygeos/pygeos/blob/e83fc031d97ed232fcd3c117bfb4fc22df925da0/pygeos/set_operations.py#L162-L172

I was wondering if `axis=None` wouldn't be a better default (in which case it always gives a single geometry by default, regardless of the shape of the array), since that is also the default of numpy reductions (eg sum). Or did we have a specific reason to have the axis=0 deviation?

**Comment by jorisvandenbossche** [comment]
@caspervdw an opinion here?

(in addition to the default axis, there is also a naming issue with Shapely, where this is called ``unary_union``. When integrating with Shapely, I think we certainly want to keep `unary_union` for backwards compatibility, but then the question is if we *also* keep `union_all`)

**Comment by jorisvandenbossche** [comment]
> but then the question is if we also keep union_all

Or we could have `unary_union` as the alias of `union_all(.., axis=None)`. 
(although I think there are also good arguments for changing the default argument for `union_all` as well)

**Comment by caspervdw** [comment]
Not sure what I was thinking when putting `axis=0` as a default. It certainly makes more sense to follow numpy's defaults here. So I am :+1: on doing `axis=None` as default.

**Comment by jorisvandenbossche** [comment]
> Not sure what I was thinking when putting axis=0 as a default. It certainly makes more sense to follow numpy's defaults here. So I am +1 on doing axis=None as default.

BTW, numpy's `ufunc.reduce` has a default of `axis=0` (I just realized), so it was certainly not that strange to use that default here as well. 
Basically in numpy you have the `.reduce` versions of ufuncs which `axis=0` as default, and the reduction functions wrapping this ufunc that have `axis=None` as default (eg `np.maximum.reduce` vs `np.max`). 

Now, I would personally put `union_all` in this second category of a direct user-facing reduction function, and so still think the change to `axis=None` as default was good.
