### ISSUE TITLE
Migrate from Travis / Appyeyor to Github Actions

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#198]
GeoPandas recently [migrated from Travis / Appveyor to Github Actions](https://github.com/geopandas/geopandas/pull/1576) thanks to the hard work of @adriangb.

This simplifies the platform-specific maintenance of configuration files; particularly applicable for integrating Cython as per #51.

As part of this, I think we should create conda environment yml files for each environment we're testing (similar to geopandas).  Will be easier to maintain than deps specified via testing matrix.

**Comment by jorisvandenbossche** [comment]
I think the GitHub Actions certainly give a nice, unified interface. 
Regarding dependencies, pygeos has much less dependencies compared to geopandas (only numpy and GEOS versions), so it might be less worth the overhead of having environment files.

That said, I *personally* think it is more useful to focus "infrastructural" effort towards Shapely. I am actively working on integrating pygeos into Shapely, and so soon we will have to deal with Shapely's CI, and improving it here won't make that easier .. 
(to be clear, I don't want to say that you shouldn't do this (it might also be easier to experiment with it here as in shapely), just that it's not a priority *for me*. And actual code improvements are of course still focused here)
