### ISSUE TITLE
Raising GEOS "notice" messages as warnings not working?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#214]
From the logging discussion at https://github.com/Toblerity/Shapely/issues/998

Currently, PyGEOS uses warnings for the "notice" messages of GEOS (and exceptions for "error" messages).

Looking into the GEOS source code to see what these "notices" are used for, I *think* it is actually only used for the `is_valid` operation (see https://github.com/libgeos/geos/blob/27516e0bdb7526699c00fef328c61561ab7a4b47/capi/geos_ts_c.cpp#L688). All other errors are sent to the "error" handler. 

But, I am actually not able to produce an example code that raises a warning ...  
From my reading of the GEOS code, I expected that this would raise a warning:

```
In [1]: import warnings

In [2]: warnings.simplefilter("always")

In [3]: import pygeos

In [4]: coords = [(0, 0), (0, 2), (1, 1), (2, 2), (2, 0), (1, 1), (0, 0)]

In [5]: bowtie = pygeos.polygons(coords)

In [6]: pygeos.is_valid(bowtie)
Out[6]: False

In [7]: pygeos.is_valid_reason(bowtie)
Out[7]: 'Ring Self-intersection[1 1]'
```

So not fully sure the warning capture in pygeos is actually working.

As comparison, with Shapely and setting up the logger to print to stdout, the equivalent example does show the message from GEOS:

```python
import sys
import logging

logger = logging.getLogger('shapely.geos')
logging_handler_out = logging.StreamHandler(sys.stdout)
logger.addHandler(logging_handler_out)
logger.setLevel(logging.INFO)

from shapely.geometry import Polygon

coords = [(0, 0), (0, 2), (1, 1), (2, 2), (2, 0), (1, 1), (0, 0)]
bowtie = Polygon(coords)

In [9]: bowtie.is_valid
Ring Self-intersection at or near point 1 1
Out[9]: False
```

**Comment by jorisvandenbossche** [comment]
(sidenote: I am not sure I would find it actually useful that `is_valid` would raise a flood of warnings in case you have invalid ones, because in the end the reason you are using `is_valid` is exactly to check that, and the boolean result can tell you if there are invalid geometries or not, for that you don't need the warning ..)

**Comment by brendan-ward** [comment]
> raise a flood of warnings in case you have invalid ones

Would it be possible to consolidate the warnings into a simpler message that indicates user should check `is_valid_reason` to get specific reasons, rather than logging each warning to stdout?

That said, I'm not sure warning is useful in this case for the reason you describe above.

**Comment by caspervdw** [comment]
> raise a flood of warnings in case you have invalid ones

That is exactly my experience when using geodjango's bindings to GEOS. Very annoying. I think I disabled that specific logger more than once. They handle the notice like this:

https://github.com/django/django/blob/486a8dae2d87e287ae24c9edda1abf0c3132af80/django/contrib/gis/geos/libgeos.py#L79

**Comment by jorisvandenbossche** [comment]
Moved this to https://github.com/shapely/shapely/issues/1283
