### ISSUE TITLE
API: get_num_geometries returning -1 for missing values?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#218]
Copying @brendan-ward's comment from https://github.com/pygeos/pygeos/pull/197#issuecomment-716961714:

> I just added a fix here for an unexpected result: `get_num_geometries` returns -1 for `None` elements in the array.  Other than where this is returned in `ufuncs.c`, I don't see that we are specifically testing for that result nor declaring it to the user via docstrings, etc.  Is this a documentation / testing gap, or is it a bug?   (related functions declare -1 as expected result for non-geometries)

So as a practical example:

```
In [1]: import pygeos

In [2]: arr = [pygeos.Geometry("POINT (0 0)"), pygeos.Geometry("POINT EMPTY"), None]

In [3]: pygeos.get_num_geometries(arr)
Out[3]: array([ 1,  1, -1], dtype=int32)
```

Personally, I would say that returning 0 makes more sense, certainly because a "count" is something you typically sum (like you were doing in this PR), and then such -1 values will be very confusing / leading to subtle bugs.

**Comment by jorisvandenbossche** [comment]
Note, it's not only the number of geometries, but also number of coordinates / points / rings:

```python
In [1]: import pygeos

In [2]: arr = pygeos.from_wkt(["POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0))", "POINT (0 0)", "POINT EMPTY", None])

In [3]: pygeos.get_num_geometries(arr)
Out[3]: array([ 1,  1,  1, -1], dtype=int32)

In [4]: pygeos.get_num_coordinates(arr)
Out[4]: array([ 5,  1,  0, -1], dtype=int32)

In [5]: pygeos.get_num_points(arr)
Out[5]: array([ 0,  0,  0, -1], dtype=int32)

In [6]: pygeos.get_num_interior_rings(arr)
Out[6]: array([ 0,  0,  0, -1], dtype=int32)
```

So for example for `get_num_coordinates`, returning 0 for missing of course would not distinguish it anymore from empty geometries. But if needed the user can check for this explicitly.

**Comment by brendan-ward** [comment]
I agree.  I think 0 is a better return value for these cases.

@caspervdw -1 is hardcoded as the result for `None` in `ufuncs.c`.  Was there a larger reason for that decision that we're not able to see from the code that would prevent us from refactoring this to return 0 instead?
