### ISSUE TITLE
RFC: Bulk geometry creation

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#241]
There have been quite some issues revolving around the geometry-creation functions:

#138 - Create geometries with different number of points in a vectorized way
#149 - Allow creating empty geometries in constructive functions

And the inverse of this, disassembling geometries into ndarrays:

#75 - ENH: get coordinates + offset arrays for "ragged array" representation
#93 - Add cython algo to get offset arrays for flat coordinates representation
#127 - Function to "flatten" or "explode" multi-geometries
#128 - Function to return all parts of a multi-geometry as ndarray
#197 - Cython + implement `get_parts`

The current geometry creation API was modeled after shapely's constructors. Now that we are integrating shapely and pygeos, I think this similarity will become less important. Shapely will keep wrapping the low level functions of pygeos (or later: shapely itself).
So at this point I think it is a good idea to make an RFC for the geometry creating functions in pygeos.

**General**
It mostly boils down to: how to you represent a ragged array in numpy? I think we have two options:

- An ndarray of python lists. While not optimal in terms of performance, it is still sufficiently performant for pygeos to support this. Lists are actually not that bad.
- We have discussed the (coordinates, indices) approach extensively in the context of `get_parts` (see #128). This seems to be the most optimal approach.

Other considerations:
- We can easily support multiple creation algorithms.
- Each function needs an inverse (like `get_parts`). Naming proposal: prefix the function with `unpack_`, and change `from` to ` to`.
- We have to consider 2D and 3D
- We have to consider empty geometry creation

**Points**
*Create an n-dimensional array of 2D/3D points:*
Call signature: `points(coordinates : ndarray[shape=(..., 2/3), dtype=float])`
```
>>> points(np.array([[0, 0], [0, 1]]))
ndarray([<Geometry POINT (0 0)>, <Geometry POINT (0 1)>])
>>> points(np.array([[0, 0, 0], [0, 1, 1]]))
ndarray([<Geometry POINT Z (0 0 0)>, <Geometry POINT Z (0 1 1)>])
```
*Create an n-dimensional array of mixed points from lists*
Call signature: `points_from_lists(coordinates : ndarray[dtype=list])`
```
>>> points_from_lists([[0, 0], [0, 1, 1], []]))
ndarray([<Geometry POINT (0 0)>, <Geometry POINT Z (0 1 1)>, <Geometry POINT EMPTY>])
```

**Linestrings and linearrings**
*Create a 1-dimensional array of 2D/3D linestrings*:
Call signature: `linestrings_1d(coordinates : ndarray[N, 2/3, dtype=float], indices : ndarray[N, dtype=int])`
```
>>> linestrings_1d(np.array([[0, 0], [0, 1], [0, 0], [0, 2]]), np.array([0, 0, 1, 1]))
ndarray([<Geometry LINESTRING (0 0, 0 1)>, <Geometry LINESTRING (0 0, 0 2)>])
```
*Create an n-dimensional array of 2D/3D linestrings of fixed length M*:
Call signature: `linestrings_equal_size(coordinates : ndarray[..., M, 2/3, dtype=float])`
```
>>> linestrings_equal_size(np.array([[[0, 0], [0, 1]], [[0, 0], [0, 2]]]))
ndarray([<Geometry LINESTRING (0 0, 0 1)>, <Geometry LINESTRING (0 0, 0 2)>])
```
*Create an n-dimensional array of mixed linestrings from lists of points*:
Call signature: `linestrings_from_points(coordinates : ndarray[N, dtype=list of Points], ndim : int = 2)`
```
>>> linestrings_from_points(ndarray([[<Geometry POINT (0 0)>, <Geometry POINT Z (0 1 1)>]]))
ndarray([<Geometry LINESTRING (0 0, 0 1)>])
>>> linestrings_from_points(ndarray([[<Geometry POINT (0 0)>, <Geometry POINT Z (0 1 1)>]]), ndim=3)
ndarray([<Geometry LINESTRING Z (0 0 nan, 0 1 1)>])
```

**Polygons**
Without holes: same as linestrings / linearrings
With holes: same as collections

**Collections**
*Create a 1-dimensional array of collections*
Call signature: `collections_1d(geometries : ndarray[N, dtype=Geometry], indices : ndarray[N, dtype=int], collection_type : GeometryType = GeometryType.GEOMETRYCOLLECTION, ndim : int = 2)`
```
>>> collections_1d(np.array([<Geometry POINT (0 0)>, <Geometry LINESTRING (0 0, 0 1)>, <Geometry LINESTRING (0 0, 0 2)>]), np.array([0, 1, 1]))
ndarray([<Geometry GEOMETRYCOLLECTION (POINT (0 0))>, <Geometry GEOMETRYCOLLECTION (LINESTRING (0 0, 0 1), LINESTRING (0 0, 0 2))>])
```
*Create an n-dimensional array of collections of size M*
Call signature: `collections_equal_size(geometries : ndarray[..., M, dtype=Geometry], collection_type : GeometryType = GeometryType.GEOMETRYCOLLECTION, ndim : int =2)`
```
>>> collections_equal_size(np.array([[<Geometry POINT (0 0)>, <Geometry POINT (0 1)>], [<Geometry POINT (1 0)>, <Geometry POINT (1 1)>]]))
ndarray([<Geometry GEOMETRYCOLLECTION (POINT (0 0), POINT (0 1))>, <Geometry GEOMETRYCOLLECTION (POINT (1 0), POINT (1 1))>])
```
*Create an n-dimensional array of collections from lists of geometries*
Call signature: `collections_from_lists(geometries : ndarray[..., dtype=list of Geometry], collection_type : GeometryType = GeometryType.GEOMETRYCOLLECTION, ndim : int = 2)`
```
>>> collections_from_lists([[<Geometry POINT (0 0)>, <Geometry POINT (0 1)>], [<Geometry POINT (1 0)>], []]))
ndarray([<Geometry GEOMETRYCOLLECTION (POINT (0 0), POINT (0 1))>, <Geometry GEOMETRYCOLLECTION (POINT (1 0))>, GEOMETRYCOLLECTION EMPTY])
```

**Empty geometries**
*Create an n-dimensional array of empty points*
Call signature: `empty(shape : tuple or None = None, geom_type : enum = GeometryType.POINT, ndim : int = 2)`
```
>>> empty()
<Geometry POINT EMPTY>
>>> empty(ndim=3)
<Geometry POINT Z EMPTY>
>>> empty(geom_type=GeometryType.LINESTRING)
<Geometry LINESTRING EMPTY>
>>> empty((2, ))
ndarray([<Geometry POINT EMPTY>, <Geometry POINT EMPTY>])
```

@jorisvandenbossche @brendan-ward  What do you think about these proposals?

**Comment by brendan-ward** [comment]
Thanks for pulling this together @caspervdw .

I'm not entirely sure I follow every suggestion, but I had a few thoughts:

I prefer the existing naming without `create_` prefix, since this follows numpy more closely (`np.array([...])` vs `np.create_array([...])`) and is still sufficiently clear.  

I can see a potential need to create a singular empty geometry of a given type, but I'm having a harder time imagining a use case for creating an array of empty geometries.  But if there is a case, something perhaps closer to numpy's `empty` function, which would take dimensions and instead of `dtype`, take a named geometry type (e.g., `pygeos.empty(shape=(10,), type='Polygon', ndim=2/3)`).  Or the geometry specific functions would be fine too, e.g., `pygeos.empty(shape=(10,), ndim=2/3)`.  Not sure if this should enable multiple axes; I've only ever worked with geometries in 1D arrays).

I think I need help understanding some use cases for n-dimensional geometries, otherwise it is hard to get my head around the n-dimensional variants described above.

I'm not following the suggestion about `_unpack`.  Is `get_parts` the `_unpack` equivalent of a Multi*, and returning a ragged array of points + indices the `_unpack` equivalent for a LineString?

I do continue to like the idea of returning geometries plus indices for operations that return a different output array size than the input, esp. for those that have a larger size (e.g., get parts); this allows us to easily join back any associated information with those parts (i.e., other columns in a pandas DataFrame).

**Comment by caspervdw** [comment]
Thanks for your feedback. I included most of it in the RFC text. See below for some reactions on your remarks:

> I prefer the existing naming without `create_` prefix, since this follows numpy more closely (`np.array([...])` vs `np.create_array([...])`) and is still sufficiently clear.

Agreed. The inverse could be prefixed with `unpack`. Then the current `get_parts` would become `unpack_collections_1d`.

> I can see a potential need to create a singular empty geometry of a given type, but I'm having a harder time imagining a use case for creating an array of empty geometries. But if there is a case, something perhaps closer to numpy's `empty` function, which would take dimensions and instead of `dtype`, take a named geometry type (e.g., `pygeos.empty(shape=(10,), type='Polygon', ndim=2/3)`). Or the geometry specific functions would be fine too, e.g., `pygeos.empty(shape=(10,), ndim=2/3)`. Not sure if this should enable multiple axes; I've only ever worked with geometries in 1D arrays).

Good idea to include a `type` parameter and enable this for all geometry types. The `shape` is necessary to stick to the "everything is vectorized" philosophy of pygeos.

> I think I need help understanding some use cases for n-dimensional geometries, otherwise it is hard to get my head around the n-dimensional variants described above.

I added some examples. They are pretty verbose though...

> I'm not following the suggestion about `_unpack`. Is `get_parts` the `_unpack` equivalent of a Multi*, and returning a ragged array of points + indices the `_unpack` equivalent for a LineString?

The `unpack_collections_1d` would return geometries, indices (as `get_parts` does). The `unpack_linestrings_1d` would return an (N, 2) shaped array and indices. `unpack_collections_to_lists` would return lists of lists of geometries.

**Comment by Aniwax** [comment]
At the moment, I can use `shapely.polygon.Polygon([]) `to construct an empty polygon, then convert it to pygeos using `pygeos.from_shapely()` and I didn't receive any error message for creating an empty polygon in this way.

**Comment by caspervdw** [comment]
@Aniwax I am certainly positive on the implementation of `pygeos.empty(shape: tuple, geom_type: GeometryType)`.

In the meantime you could use `pygeos.polygons(None)`. As of pygeos 0.10, this will yield an empty polygon.

**Comment by Aniwax** [comment]
Great, thank you 💯  @caspervdw

**Comment by caspervdw** [comment]
The remaining work on `pygeos.empty` is covered by #149 - closing.
