### ISSUE TITLE
API: ufuncs vs wrapped python functions

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#25]
While playing around a bit with the latest version, I noticed that the top-level functions are not the ufuncs, but python wrapper functions (https://github.com/caspervdw/pygeos/blob/master/pygeos/predicates.py):

```
In [2]: pygeos.contains
Out[2]: <function pygeos.predicates.contains(a, b, **kwargs)>

In [3]: pygeos.ufuncs.contains
Out[3]: <ufunc 'contains'>
```

I was just wondering, is there a specific reason for this? 
Is it for adding a docstring? (if it is only that, I think this can be added to the ufuncs directly as well)

**Comment by caspervdw** [comment]
I actually liked wrapping it into python functions. It has the following advantages:

- docstrings are readable from the code (they have to be on C level else, you can’t change a __doc__ attribute of a ufunc dynamically)
- doctests are possible
- some python-level preprocessing is possible

`kwargs` are propagated so most of the ufunc stuff is accessible.

There is some ufunc functionality missing, but I didn’t see any use cases of these. 

Of course I am open for other approaches.

**Comment by adriangb** [comment]
I found a case where this is a bit of a drawback:

Numpy ufuncs have some nice built in functions like [`reduce`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html).
```python3
np.multiply.reduce([2,3,5])
30
```

This also works with pygeos ufuncs, but only through `pygeos.lib`.
```python3
pygeos.difference.reduce([...])  # does not work
pygeos.lib.difference.reduce([...])  # works fine
```

**Comment by jorisvandenbossche** [comment]
As you figured out in the meantime (based on the edit of your post ;)), setting the `__doc__` directly on the ufunc is not allowed.

Of course, the docstrings can also be put in a text file and parsed and added in C, but that adds some complexity.

> Here is an admittedly hacky workaround I came up with:

That's potentially a neat trick. One problem though is that not all functions are simply calling their `lib.` version (although many do). Some function do some pre/post-processing, or pass through keywords converted to numpy types.

It might also be an option to still have the raw ufuncs available for "power users", as is now the case actually with `pygeos.lib`, and regard this as more or less officially supported (although that gives a bigger API surface to maintain ..)

**Comment by adriangb** [comment]
> That's potentially a neat trick. One problem though is that not all functions are simply calling their `lib.` version (although many do). Some function do some pre/post-processing, or pass through keywords converted to numpy types.

Right, this would only really work with functions that do not have pre/post processing (which is a lot of them, actually). For the rest, I guess we could just not expose that functionality.

> It might also be an option to still have the raw ufuncs available for "power users", as is now the case actually with `pygeos.lib`, and regard this as more or less officially supported (although that gives a bigger API surface to maintain ..)

I still do think it would be nice to have the ufunc attatched to the python function in some way (although most are obvious). We could add a `ufunc` attribute using a method similar to the above.

**Comment by adriangb** [comment]
Yet another option would be to wrap using a callable class instead of a function. Shown by example:

```python3
import numpy as np
from . import lib, Geometry, GeometryType

__all__ = [
    "union",
]


class UfuncWrapper:

    def __init__(self, ufunc):
        self.ufunc = ufunc

    def __call__(self, *args, **kwargs):
        return self.ufunc(*args, **kwargs)

    def reduce(self, *args, **kwargs):
        return self.ufunc.reduce(*args, **kwargs)


class Union(UfuncWrapper):
    """Merges geometries into one.
    Parameters
    ...
    """

    def __call__(self, a, b, **kwargs):
        return self.ufunc(a, b, **kwargs)

    def reduce(self, geometries, axis=0, **kwargs):
        """Returns the union of multiple geometries.
        Parameters
        ...
        """
        geometries = np.asarray(geometries)
        if axis is None:
            geometries = geometries.ravel()
        else:
            geometries = np.rollaxis(
                np.asarray(geometries), axis=axis, start=geometries.ndim
            )
        # create_collection acts on the inner axis
        collections = lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
        return lib.unary_union(collections, **kwargs)


union = Union(lib.union)
```

```
>> from ... import union
>> help(union)
```
```
class Union(UfuncWrapper)
 |  Union(ufunc)
 |  
 |  Merges geometries into one.
 |  Parameters
```
```
>> help(union.reduce)
```
```
reduce(geometries, axis=0, **kwargs) method of pygeos.test_wrap.Union instance
    Returns the union of multiple geometries.
    Parameters
    ...
```

I think this is the cleanest and most flexible way, but evidently the docstrings can still be a bit confusing (it's a class?), which kind of defeats the original intent.
