### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#250]
@jorisvandenbossche  @brendan-ward  I think it is good to start aiming for a release. Can you take a look at the milestone I created and add what you think is necessary for the release?

https://github.com/pygeos/pygeos/milestone/4

**Comment by jorisvandenbossche** [comment]
It would indeed be good to do a release, thanks for bringing this up. Looking at the open issues tagged with the milestone, I don't think there is any that is critical to include? 
(maybe `reverse` since that is basically ready, and maybe `is_prepare` since that is related to the other new prepare functionality?)

**Comment by caspervdw** [comment]
Discussed over google meet with @jorisvandenbossche , after #282 is in, we are going to release 0.9

**Comment by brendan-ward** [comment]
@caspervdw could this please include #276 ?  It is ready to go.

**Comment by jorisvandenbossche** [comment]
Would be good to merge https://github.com/pygeos/pygeos/pull/283 to fix the styling issue in the docstrings online (if it works) as well

**Comment by caspervdw** [comment]
OK, everything ready! I may have time tonight to do the release.

**Comment by jorisvandenbossche** [comment]
@caspervdw Could you take a quick look at https://github.com/pygeos/pygeos/pull/276 if possible? (it's ready and I already reviewed it, would be nice to include)

**Comment by caspervdw** [comment]
OK, it is done, i tested the sdist in a clean venv and everything is OK.

Work will continue in:
- https://github.com/conda-forge/pygeos-feedstock
- https://github.com/pygeos/pygeos-wheels

**Comment by caspervdw** [comment]
Done!

**Comment by jorisvandenbossche** [comment]
Thanks for the release!
