### ISSUE TITLE
CI: Add linting step to Github Actions

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#251]
We may want to do this step last so that we get early feedback about builds / tests passing across the OS / python / deps matrix.

Should run:
* `black` for Python files
* `clang-format for C files

Cython files currently do not have a formatter / linter available that I know about; we may want to fall back to checking line length only.

**Comment by caspervdw** [comment]
Maybe we should start using `pytest-black` and/or `pytest-flakes`. I also like to use `isort`, but it has to be tweaked to be able to combine it with `black`.

Also, I have good experience using pre-commit hooks  (https://github.com/pre-commit/pre-commit)

**Comment by jorisvandenbossche** [comment]
> Maybe we should start using pytest-black 

What's the value of `pytest-black` compared to just `black` ? (don't really get that from their readme)

I am personally in favor, at least for python code; for C code it might be harder to require this every contributor to have it installed/set-up (but probably also something to discuss with Shapely devs). 
But if we start requiring it, I agree we should use pre-commit, I also have good experience with it using it for pandas and black (or at least have a configuration, and recommend contributors to use it; it shouldn't be a hard requirement of course)

**Comment by caspervdw** [comment]
Solved in #328
