### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alexvaler** [pygeos/pygeos#271]
PyGEOS not working

----> 2 import pygeos

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\pygeos\__init__.py in <module>
----> 1 from .lib import GEOSException  # NOQA
      2 from .lib import Geometry  # NOQA
      3 from .lib import geos_version, geos_version_string  # NOQA
      4 from .lib import geos_capi_version, geos_capi_version_string  # NOQA
      5 from .decorators import UnsupportedGEOSOperation  # NOQA

ImportError: DLL load failed while importing lib: Не найдена указанная процедура.

python '3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]' on windows 10 19042.685
OSGeo4W64 installed
GEOS_LIBRARY_PATH = C:\OSGeo4W64\lib\geos_c.dll 
GEOS_INCLUDE_PATH = C:\OSGeo4W64\include

How can i fix it?

**Comment by jorisvandenbossche** [comment]
How did you install pygeos?

**Comment by alexvaler** [comment]
pip install pygeos

another option:

C:\WinPython\WPy64-3902\scripts>pip install pygeos --no-binary :all:
Collecting pygeos
  Using cached pygeos-0.8.tar.gz (74 kB)
Requirement already satisfied: numpy>=1.10 in
c:\winpython\wpy64-3902\python-3.9.0.amd64\lib\site-packages (from pygeos)
(1.19.4+mkl)
Skipping wheel build for pygeos, due to binaries being disabled for it.
Installing collected packages: pygeos
    Running setup.py install for pygeos ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\WinPython\WPy64-3902\python-3.9.0.amd64\python.exe' -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\Alex\\AppData\\Local\\Temp\\pip-install-4vy2bzsy\\pygeos_0a043292c65c4250a4214ee3259333e0\\setup.py'"'"';
__file__='"'"'C:\\Users\\Alex\\AppData\\Local\\Temp\\pip-install-4vy2bzsy\\pygeos_0a043292c65c4250a4214ee3259333e0\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
'C:\Users\Alex\AppData\Local\Temp\pip-record-03fzun39\install-record.txt'
--single-version-externally-managed --compile --install-headers
'C:\WinPython\WPy64-3902\python-3.9.0.amd64\Include\pygeos'
         cwd:
C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\
    Complete output (181 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\pygeos
    copying pygeos\constructive.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\coordinates.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\creation.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\decorators.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\geometry.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\io.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\linear.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\measurement.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\predicates.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\set_operations.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\strtree.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\_version.py -> build\lib.win-amd64-3.9\pygeos
    copying pygeos\__init__.py -> build\lib.win-amd64-3.9\pygeos
    running egg_info
    writing pygeos.egg-info\PKG-INFO
    writing dependency_links to pygeos.egg-info\dependency_links.txt
    writing requirements to pygeos.egg-info\requires.txt
    writing top-level names to pygeos.egg-info\top_level.txt
    reading manifest file 'pygeos.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pygeos\*.dll'
    writing manifest file 'pygeos.egg-info\SOURCES.txt'
    UPDATING build\lib.win-amd64-3.9\pygeos/_version.py
    set build\lib.win-amd64-3.9\pygeos/_version.py to '0.8'
    running build_ext
    building 'pygeos.lib' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\src
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/coords.c
/Fobuild\temp.win-amd64-3.9\Release\src/coords.obj
    coords.c

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(227):
warning C4244: =: преобразование "Py_ssize_t" в "int", возможна потеря
данных

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/geos.c
/Fobuild\temp.win-amd64-3.9\Release\src/geos.obj
    geos.c

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/lib.c
/Fobuild\temp.win-amd64-3.9\Release\src/lib.obj
    lib.c

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(227):
warning C4244: =: преобразование "Py_ssize_t" в "int", возможна потеря
данных

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/pygeom.c
/Fobuild\temp.win-amd64-3.9\Release\src/pygeom.obj
    pygeom.c

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/strtree.c
/Fobuild\temp.win-amd64-3.9\Release\src/strtree.obj
    strtree.c

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(227):
warning C4244: =: преобразование "Py_ssize_t" в "int", возможна потеря
данных

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\cl.exe /c
/nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\OSGeo4W64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\include
-IC:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include
-IC:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\include -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files
(x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tcsrc/ufuncs.c
/Fobuild\temp.win-amd64-3.9\Release\src/ufuncs.obj
    ufuncs.c

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\numpy\core\include\numpy/npy_3kcompat.h(227):
warning C4244: =: преобразование "Py_ssize_t" в "int", возможна потеря
данных

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(10):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(11):
warning C4068: неизвестная прагма "GCC"

C:\Users\Alex\AppData\Local\Temp\pip-install-4vy2bzsy\pygeos_0a043292c65c4250a4214ee3259333e0\src\geos.h(13):
warning C4068: неизвестная прагма "GCC"
    src/ufuncs.c(122): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(122): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(122): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(149): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(149): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(149): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(193): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(193): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(193): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(280): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(293): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(307): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(307): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(307): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(368): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(379): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(393): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(393): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(393): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(509): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(523): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(537): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(537): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(537): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(650): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(660): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(674): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(674): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(674): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(735): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(735): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(735): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(802): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(802): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(802): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(872): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(872): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(872): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(908): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(908): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(908): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(989): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1007): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1007): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1007): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1040): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1051): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1065): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1065): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1065): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1094): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1094): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1094): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1123): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1135): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1149): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1149): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1149): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1179): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1191): warning C4244: функция: преобразование "npy_intp" в
"int", возможна потеря данных
    src/ufuncs.c(1205): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1205): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1205): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1238): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1238): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1238): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1273): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1273): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1273): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1284): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1287): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1297): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1297): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1297): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1312): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1316): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1327): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1327): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1327): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1353): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1357): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1364): warning C4244: функция: преобразование "npy_intp" в
"unsigned int", возможна потеря данных
    src/ufuncs.c(1375): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1375): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1375): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1412): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1412): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1412): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1476): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1476): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1476): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1541): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1541): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1541): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1609): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1609): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1609): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1662): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1662): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1662): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1709): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1709): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1709): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1791): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1791): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1791): warning C4028: формальный параметр 3 отличается от
объявления
    src/ufuncs.c(1847): warning C4090: функция: разные квалификаторы "const"
    src/ufuncs.c(1847): warning C4028: формальный параметр 2 отличается от
объявления
    src/ufuncs.c(1847): warning C4028: формальный параметр 3 отличается от
объявления
    C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\link.exe
/nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO
/LIBPATH:C:\OSGeo4W64\lib\geos_c.dll
/LIBPATH:C:\WinPython\WPy64-3902\python-3.9.0.amd64\libs
/LIBPATH:C:\WinPython\WPy64-3902\python-3.9.0.amd64\PCbuild\amd64
/LIBPATH:C:\Program Files (x86)\Microsoft Visual
Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\lib\x64
/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64
/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64
geos_c.lib /EXPORT:PyInit_lib
build\temp.win-amd64-3.9\Release\src/coords.obj
build\temp.win-amd64-3.9\Release\src/geos.obj
build\temp.win-amd64-3.9\Release\src/lib.obj
build\temp.win-amd64-3.9\Release\src/pygeom.obj
build\temp.win-amd64-3.9\Release\src/strtree.obj
build\temp.win-amd64-3.9\Release\src/ufuncs.obj
/OUT:build\lib.win-amd64-3.9\pygeos\lib.cp39-win_amd64.pyd
/IMPLIB:build\temp.win-amd64-3.9\Release\src\lib.cp39-win_amd64.lib
    LINK : fatal error LNK1181: не удается открыть входной файл "geos_c.lib"
    error: command 'C:\\Program Files (x86)\\Microsoft Visual
Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\link.exe'
failed with exit code 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1:
'C:\WinPython\WPy64-3902\python-3.9.0.amd64\python.exe' -u -c 'import sys,
setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\Alex\\AppData\\Local\\Temp\\pip-install-4vy2bzsy\\pygeos_0a043292c65c4250a4214ee3259333e0\\setup.py'"'"';
__file__='"'"'C:\\Users\\Alex\\AppData\\Local\\Temp\\pip-install-4vy2bzsy\\pygeos_0a043292c65c4250a4214ee3259333e0\\setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
'C:\Users\Alex\AppData\Local\Temp\pip-record-03fzun39\install-record.txt'
--single-version-externally-managed --compile --install-headers
'C:\WinPython\WPy64-3902\python-3.9.0.amd64\Include\pygeos' Check the logs
for full command output.

пт, 11 дек. 2020 г. в 13:03, Joris Van den Bossche <notifications@github.com

**Comment by jorisvandenbossche** [comment]
You provided the `--no-binary` option, which means that pygeos is built from source, and you can see in the output above that this errored. I would recommend to install prebuilt binaries (either a wheel with pip, or otherwise use conda)

**Comment by alexvaler** [comment]
I start with it 
C:\WinPython\WPy64-3902\scripts>pip install pygeos
Collecting pygeos
  Using cached pygeos-0.8-cp39-cp39-win_amd64.whl
Requirement already satisfied: numpy>=1.10 in c:\winpython\wpy64-3902\python-3.9.0.amd64\lib\site-packages (from pygeos) (1.19.4+mkl)
Installing collected packages: pygeos
Successfully installed pygeos-0.8

----> 2 import pygeos

C:\WinPython\WPy64-3902\python-3.9.0.amd64\lib\site-packages\pygeos\__init__.py in <module>
----> 1 from .lib import GEOSException  # NOQA
      2 from .lib import Geometry  # NOQA
      3 from .lib import geos_version, geos_version_string  # NOQA
      4 from .lib import geos_capi_version, geos_capi_version_string  # NOQA
      5 from .decorators import UnsupportedGEOSOperation  # NOQA

ImportError: DLL load failed while importing lib: Не найден указанный модуль.

**Comment by mwtoews** [comment]
Probably the issue is that binary wheels are not yet available for Python 3.9.

A workaround, if possible, is to use an older version of Python until these are ready.

**Comment by alexvaler** [comment]
Thank you for the clarification.

пн, 14 дек. 2020 г., 21:52 Mike Taves <notifications@github.com>:
