### ISSUE TITLE
Support STRtree pickling

### ISSUE THREAD

**Issue by martinfleis** [pygeos/pygeos#274]
STRtree is currently not pickable. Not sure how that could be done but shapely's  (1.7) implementation can be pickled as well as `rtree`. We tried to do some parallelisation using `joblib` and that would require pickle support. I guess that it will also be relevant for `dask-geopandas`.

```py
import pygeos
import pickle

tree = pygeos.STRtree(pygeos.points([(0, 1), (5, 0)]))
with open('tree.pickle','wb') as f:
    pickle.dump(tree, f)
```
```py
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-af80c855aa7f> in <module>
      2 
      3 with open('tree.pickle','wb') as f:
----> 4     pickle.dump(tree, f)

TypeError: can't pickle pygeos.lib.STRtree objects
```

**Comment by jorisvandenbossche** [comment]
There was recently some discussion about it on the Shapely github as well: https://github.com/Toblerity/Shapely/issues/1033

In general, GEOS does not support serializing trees (as far as I know, but it would be nice to have). What Shapely does to make the STRtree picklable, is "simply" pickling the underlying geometries, and recreate the tree when unpickling (https://github.com/Toblerity/Shapely/blob/4fcf83523dbe96fcc51fe12b6826a6ecdc4b2a66/shapely/strtree.py#L84-L97).

That's certainly not nice from a performance perspective (and it can be surprising, as you would not expect that in general from unpickling). But in general for parallel/performance-sensitive applications, it might be more important to actually have an strtree,  and pay for the additional cost of recreating it.

**Comment by jorisvandenbossche** [comment]
> But in general for parallel/performance-sensitive applications, it might be more important to actually have an strtree, and pay for the additional cost of recreating it.

Actually, of course in context of geopandas, we are already picking the geometries as part of the geometry column, and when there is no index available, it will also be recreated on first usage. So from that perspective it would of course only be duplicative to do the same for the STRtree stored in the `sindex` .. So for that application, making the STRtree picklable in this "dummy" way would not actually be helpful. 

(it might be helpful in general, though, in which case we could still handle this over at geopandas to avoid a duplicated pickling/unpickling of the geometries)

**Comment by martinfleis** [comment]
This is interesting. In such a case, https://github.com/geopandas/geopandas/pull/1747 already does that within geopandas.

**Comment by caspervdw** [comment]
I created a feature request at GEOS for the dumping/loading of built tree objects: https://trac.osgeo.org/geos/ticket/1130
