### ISSUE TITLE
Documentation and `improve performance by preparing` 

### ISSUE THREAD

**Issue by telemmaite** [pygeos/pygeos#277]
Current documentation states in multiple places `improve performance by preparing`. 

Is this some **upcoming** functionality that is not available yet with the latest release or I am just missing how it should be done?

**Comment by jorisvandenbossche** [comment]
@telemmaite that's indeed not yet in the latest release. 

On master (and in the next release), there is a `pygeos.prepare` function that does this: https://pygeos.readthedocs.io/en/latest/creation.html#pygeos.creation.prepare

**Comment by telemmaite** [comment]
Thank you ! Looking forward to the next release, you have done great job!
