### ISSUE TITLE
Workaround Pypy build failure (PyHash_GetFuncDef)

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#280]
See https://github.com/conda-forge/pygeos-feedstock/pull/18

PyHash_GetFuncDef is not supported in Pypy. We probably can workaround this pretty easily in pygeos.

**Comment by mattip** [comment]
I think this is done in #190 which modified the [code](https://github.com/pygeos/pygeos/pull/190/files#diff-0c9328dd1eba1f503f9c678a2c98a36c7125fc21d6068617b848ef08697e7f57L144)

**Comment by caspervdw** [comment]
That's great! I indeed see that the builds on conda-forge are passing.

Still we should run the tests with pypy before merging the conda-forge PRs. But I consider this ticket closed.
