### ISSUE TITLE
Obtaining X and Y values of LineString vertices for Multiple LineStrings

### ISSUE THREAD

**Issue by AlexanderJuestel** [pygeos/pygeos#281]
Dear PyGeos Team, 

I am currently exploring the functionalities of PyGeos and I am amazed by the performance compared to iterating over Shapely geoemtries. 

I am mostly working with GeoDataFrames for a project and use Shapely functions for underlying operations. One of them is to get the X and Y coordinates of the vertices of a list of LineStrings returned as two separate lists, one for X coordinates, one for Y coordinates. I am aware of the `get_coordinates` function but it only returns a N, 2 shaped array and the information is lost to which LineString the respective coordinate pair belongs to. Or would iterating over each point of each LineString be an alternative and then using `get_x` and `get_y`? 

Is there another function that does the trick or what would be needed to implement this in pygeos. Maybe I could give it a try. 

Currently, I am solving it the following way:

```ruby
# Extracting X coordinates
gdf['X'] = [[i[0] for i in list(gdf.loc[j].geometry.coords)] for j in range(len(gdf))]

# Extracting Y coordinates
gdf['Y'] = [[i[1] for i in list(gdf.loc[j].geometry.coords)] for j in range(len(gdf))]
```

The main aim is to improve the performance and reduce computing time for large GeoDataFrames. 

Cheers and thanks for your tips

**Comment by brendan-ward** [comment]
@AlexanderJuestel glad to hear that pygeos is working well for you.

There is some discussion around returning all results from an operation that may produce _n_ results per geometry, along with the index of the original geometries in #241 (see the `unpack` functions).  This approach is already used by `get_parts` and uses Cython to help speed up the loops versus the Python loop / list comprehension approach.


For your example, it might be possible to do something like this (limited to array of single-part lines), but (should be) faster than using list comprehension:

```
import numpy as np
import pygeos as pg

lines = gdf.geometry.values.data

# get an array of indexes aligned with output coordinates
indexes = np.repeat(np.arange(len(lines)), pg.get_num_points(lines))

# get the array of coordinates
x, y = pg.get_coordinates(lines).T

# to put them back together into a DataFrame
df = pd.DataFrame({'x': x, 'y': y}, index=indexes)
```

**Comment by AlexanderJuestel** [comment]
Hey @brendan-ward,

Thanks for your response! I will test your suggestion and will then get back here. Every speed improvement will be appreciated. 

And maybe the discussed functionality will make it into the API soon. That would be great :)

Cheers Alex

**Comment by jorisvandenbossche** [comment]
If I understand correctly what you are looking for, I think it is similar as https://github.com/pygeos/pygeos/issues/75 (but then specifically for linestrings, the example code in the issue is for polygons, which needs additional "indices" (or offsets, as I called it there) for the rings and parts). 
But indeed, the code of @brendan-ward above should be the equivalent for linestrings, based on the currently available APIs (and it should already be quite fast, I don't expect that a specific cython algo will do much better in the case of simple linestrings).

BTW, just to be sure you are aware (and it will not help for the specific question above): you can already let geopandas use pygeos under the hood (if it's installed, geopandas will detect it and use it) to speed up some operations.

**Comment by AlexanderJuestel** [comment]
Hey @jorisvandenbossche,

Thanks for your response as well!

I am familiar with the connection between geopandas and pygeos, yes. So, the work on our GemGIS package has been somewhat iterative since we initialized it last summer and my learning curve has been quite steep I think. So we started out with Geopandas and then I got more familiar with Shapely and now we are trying to speed up everything a little by going back to the roots and try to use pygeos. We are still using GeoDataFrames as the main "interface" for users since they are very handy but maybe we can speed up some of our operations by using pure pygeos and most of the time it is just doing something with the coordinates of the geometries. But that should be enough off topic talk 😉

**Comment by AlexanderJuestel** [comment]
@brendan-ward, your method with the DataFrame was a little unhandy since I needed the separate lists of coordinates, so I tried a little bit and came up with the following that yields a 10 times speed up, which is already very good! I am still using list comprehension but that will do the trick for now I think :) 

![image](https://user-images.githubusercontent.com/45469915/105354805-5bc7d180-5bf1-11eb-8c31-cb8142ce649b.png)

**Comment by AlexanderJuestel** [comment]
Closing this and hoping for a more wrapped solution in the future! :)

**Comment by Aniwax** [comment]
> Hey @jorisvandenbossche,
> 
> Thanks for your response as well!
> 
> I am familiar with the connection between geopandas and pygeos, yes. So, the work on our GemGIS package has been somewhat iterative since we initialized it last summer and my learning curve has been quite steep I think. So we started out with Geopandas and then I got more familiar with Shapely and now we are trying to speed up everything a little by going back to the roots and try to use pygeos. We are still using GeoDataFrames as the main "interface" for users since they are very handy but maybe we can speed up some of our operations by using pure pygeos and most of the time it is just doing something with the coordinates of the geometries. But that should be enough off topic talk 😉

Going through similar journey: switching from Shapely to PyGeos for better performance. The bottle neck in my code was similar `polygon.exterior.xy` was too slow using Shapely..so I am looking forward to try out pygeos :) 

It would be great if you can share some insights on the performance of these 3 packages.

**Comment by Aniwax** [comment]
Side remark to the PyGEO team @brendan-ward , it would be great if you guys can open the discussion on Github. So we can move these discussions over there :)  🔥 🔥 🔥

**Comment by brendan-ward** [comment]
@Aniwax one existing place for chat-style discussions / questions around GeoPandas / Shapely / PyGEOS is the [GeoPandas gitter](https://gitter.im/geopandas/geopandas).
