### ISSUE TITLE
DOC: Linestring and Polygon with overlaps vs crosses

### ISSUE THREAD

**Issue by telemmaite** [pygeos/pygeos#287]
Based on the documentation for [overlaps](https://pygeos.readthedocs.io/en/latest/predicates.html#pygeos.predicates.overlaps)
> Returns True if A and B intersect, but one does not completely contain the other.

I am not sure why but `overlaps` returns `False` for this case while `crosses` returns `True` ? 
![image](https://user-images.githubusercontent.com/4275711/106060102-517b6b00-60fc-11eb-9052-1a303b666650.png)
Is it expected, maybe because one of the points of the linestring is not inside the polygon?

I can provide proper coordinates if that case is interesting.

**Comment by brendan-ward** [comment]
The [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) relationships at Wikipedia look like they clarify this a bit:

Crosses
>  a crosses b: they have some but not all interior points in common, and the dimension of the intersection is less than that of at least one of them.

Overlaps
> a overlaps b: they have some but not all points in common, they have the same dimension, and the intersection of the interiors of the two geometries has the same dimension as the geometries themselves.

I think overlaps is failing on the same dimension rule.  The examples of this for [overlaps](https://postgis.net/docs/ST_Overlaps.html) in PostGIS show only same dimension comparisons, whereas [crosses](https://postgis.net/docs/ST_Crosses.html) shows mixed dimensions (line vs polygon).

We may want to consider adding a little bit more to our docs to clarify this better.

**Comment by telemmaite** [comment]
Thank you very much for the clarification, I did not thought that dimensionality should be the same between the two geometries.
because the documentation of [overlaps](https://pygeos.readthedocs.io/en/latest/predicates.html#pygeos.predicates.overlaps) gives the following example between **point** and **line**:
> overlaps(line, Geometry("POINT (0.5 0.5)"))
False

**Comment by jorisvandenbossche** [comment]
Yes, that can certainly use some clarification in the docs, especially for that example with line and point (the line actually contains the point, in this case). It might be better to use polygons for the base examples

**Comment by jorisvandenbossche** [comment]
Let's keep it open as a needed documentation enhancement
