### ISSUE TITLE
TST: Tests fail on big-endian systems

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#297]
The `s390` runner is big-endian, whereas everything else we are testing is little-endian.  Our WKB tests expect results in little-endian order, and fail on inequality ([ref](https://travis-ci.com/github/pygeos/pygeos/jobs/481129309)).

The simple solution may be to skip or xfail WKB tests on `s390`; otherwise we need to have a set of expected WKB output for each endianness.

**Comment by caspervdw** [comment]
We can also force byte order in the tests by putting `to_wkb(..., byte_order=1)` ?

**Comment by jorisvandenbossche** [comment]
There are also some doctest failures like this one:

```
063     Examples
064     --------
065     >>> from pygeos import normalize
066     >>> points = Geometry("MULTIPOINT (2 2, 4 2)")
067     >>> normalize(voronoi_polygons(points))
Expected:
    <pygeos.Geometry GEOMETRYCOLLECTION (POLYGON ((3 0, 3 4, 6 4, 6 0, 3 0)), PO...>
Got:
    <pygeos.Geometry GEOMETRYCOLLECTION EMPTY>
```

That might not be WKB related?

**Comment by brendan-ward** [comment]
Correct - not all the failures on `s390` are necessarily related to WKB; this particular one will require a bit more investigation.

**Comment by caspervdw** [comment]
The remainder can be divided into two categories:

## Failures on big endian systems with `voronoi_polygons`:

`voronoi_polygons` (`GEOSVoronoiDiagram_r`) fails in all cases:
```
>>> voronoi_polygons(Geometry("MULTIPOINT (2 2, 4 2)"))
<pygeos.Geometry GEOMETRYCOLLECTION EMPTY>
>>> voronoi_polygons(Geometry("LINESTRING (0 0, 1 0, 1 1)"))
E pygeos.GEOSException: TopologyException: Input geom 1 is invalid: Self-intersection at or near point -2.2558952938275252e+307 -2.2558952938275252e+307 at -2.2558952938275252e+307 -2.2558952938275252e+307
```
etc. The large numbers in the error message point in the direction of an assumed endianness somewhere in `GEOSVoronoiDiagram_r`

## Failures on big endian systems with predicates:

```
>>> disjoint(Geometry("LINESTRING(0 0, 1 1)"), Geometry("LINESTRING(0 2, 2 0)"))
True # expected False
>>> intersects(Geometry("LINESTRING(0 0, 1 1)"), Geometry("LINESTRING(0 2, 2 0)"))
False  # expected True
```

It seems that GEOSIntersects_r behaves differently when geometries only touch (like here) on big endian systems.

There is one more error, but I think it falls in this category too:
```
>>> tree = STRTree(pygeos.points(np.arange(10), np.arange(10)))
>>> tree.query(Geometry("LINESTRING (0 2, 2 0)"), predicate="contains_properly")
[]  # expected [1]
```
Underlying:
```
>> contains_properly(Geometry("LINESTRING (0 2, 2 0)"), Geometry("POINT (1 1)"))
False  # expected True
```

Does these two test failures ring any bells with you @pramsey?

**Comment by pramsey** [comment]
What platform are you using for these tests? We've been labouring under a lack of access to big endian architectures for some time.

**Comment by caspervdw** [comment]
S390x is one of the architectures supported by Travis, see here for our config:

https://github.com/pygeos/pygeos/blob/1b89ff7ed148ebfc5f1aea1952904cc318adcf8a/.travis.yml#L3

**Comment by caspervdw** [comment]
I think we should close this issue with "should be fixed upstream". There is really nothing we can do about it in pygeos.

Question is: how do we deal with the CI here? Skip the S390x arch for now?

**Comment by brendan-ward** [comment]
It seems OK to leave the `s390`arch test in place for now, but expect it to fail?  May help us catch other endianness-related bugs in the future.

**Comment by caspervdw** [comment]
I'll close this (#319 ) as it can only be fixed upstream
