### ISSUE TITLE
ENH: Query all STRtree geometries within search distance

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#303]
The idea came up in the GEOS IRC.

This currently can be done using a few vectorized functions:
1. buffer geometries by search distance (likely plus small epsilon)
2. query the tree using buffers as inputs and predicate='intersects'
3. relate the indexes in the buffers back to the original geometries

However, it may be more optimal to use an approach like #272 with custom callbacks to the tree query to calculate distance and an expanded envelope around the input geometries.  Performance probably depends on difference between distance calculations and prepared intersection tests.

**Comment by adriangb** [comment]
Is this as a filter before the current nearest implementation, or instead of?

**Comment by brendan-ward** [comment]
Separate function altogether: the goal is to find all geometries (indexes) within the search radius, not just the nearest ones.

**Comment by adriangb** [comment]
I see. Thanks!

**Comment by chourmo** [comment]
This is one of the interesting API in scipy KDTree that is missing in STRTree.

https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query_pairs.html#scipy.spatial.KDTree.query_pairs

The others are creating a distance matrix and a simple count_neighbors.

**Comment by jorisvandenbossche** [comment]
Somewhat related, Postgis has a "within distance" predicate function (https://postgis.net/docs/ST_DWithin.html), so an STRtree with such search feature would allow to implement something like DWithin efficiently (we could of course already implement it right now with a brute force `pygeos.within(geometries, pygeos.buffer(other, distance))`).

**Comment by ljwolf** [comment]
This would be extremely useful... @martinfleis, @darribas, we were just talking about this. 

Currently, we have this functionality using the `script.spatial.cKDTree.query_ball_tree`, but that gets quite slow for large point clouds...

**Comment by martinfleis** [comment]
@ljwolf this wouldn't be faster for points than `cKDTree`. I've tried to do this manually (buffer + `query_bulk`) and it was about 8x slower than using `cKDTree` in `libpysal.weights.DistanceBand`.

**Comment by darribas** [comment]
Just to follow up @martinfleis's point, not sure this is the proper venue, but something to explore to speed those things up might be allowing queries to be performed in parallel?

**Comment by caspervdw** [comment]
@brendan-ward Is this addressed by #402 ? Please close this ticket if so

**Comment by brendan-ward** [comment]
Effectively duplicate; closing.
