### ISSUE TITLE
Handle GEOS errors on geometry constructors

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#306]
Box fails if the second or third coordinates are NaN.

Steps to reproduce:

```
In [1]: import pygeos
In [5]: pygeos.box(1, 1, 2, float("nan"))                                                                                                                          
Out[5]: <pygeos.Geometry POLYGON ((2 1, 2 nan, 1 nan, 1 1, 2 1))>
In [6]: pygeos.box(float("nan"), 1, 2, 2)                                                                                                                          
Out[6]: <pygeos.Geometry POLYGON ((2 1, 2 2, nan 2, nan 1, 2 1))>
In [7]: pygeos.box(1, float("nan"), 2, 2)                                                                                                                          
Segmentation fault (core dumped)
In [2]: pygeos.box(1, 1, float("nan"), 2)                                                                                                                          
Segmentation fault (core dumped)
```

**Comment by caspervdw** [comment]
I narrowed it down to the LinearRing constructor. Apparently this happens when either the first or the last coordinates of a linearring has a `NaN` in it.


```
>>> pygeos.linearrings([(1, 1), (0, float("nan")), (1, 0), (1, 1)])  # OK
>>> pygeos.linearrings([(float("nan"), 1), (0, 1)), (1, 0), (1, 1)])  # segfaults
```

Before #181 was fixed, we also got segfaults when trying to construct an unclosed linearring:

```
>> pygeos.linearrings([(1, 1), (0, 1), (1, 0), (1, 2)])  # segfaults
```

Now this is fixed, but my suspicion is because `nan != nan` we can never make it work with ending coordinates being nan.

**Comment by jorisvandenbossche** [comment]
> So I think we should raise an error ourselves if the first or last coordinate is NaN

Yes, that sounds good.

**Comment by pramsey** [comment]
I tried to reproduce in GEOS, but calling the LinearRing constructor with a CoordinateSequence that includes a NaN doesn't segfault, it just throws
```
IllegalArgumentException: Points of LinearRing do not form a closed linestring
```
More (?) problematic, if you build a LineString with a NaN and then ask it isSimple() you'll also get an exception. Basically NaNs make everything bad, don't let them in.

**Comment by caspervdw** [comment]
> I tried to reproduce in GEOS, but calling the LinearRing constructor with a CoordinateSequence that includes a NaN doesn't segfault, it just throws

I dived in deeper, turns out our error handling is off. Sorry for the noise.

**Comment by caspervdw** [comment]
@pramsey  Can you help me a bit on the C++ source. I am a bit lost.

It seems that after `GEOSGeom_createLineString_r` or `GEOSGeom_createLinearRing_r` gives an exception (returns NULL), you should not clean up the coord sequence that was used to attempt construction. Am I correct in assuming that GEOS cleans up the coordinate sequence when `createLineString` errors?

**Comment by pramsey** [comment]
Yes, I found the same thing in adding a test for this. It "seems" (this is as much a C++ thing as a GEOS thing) that the CoordinateSequence ownership is passed to the owning LinearRing and added as a unique_ptr<> before the correctness checks run, so when the whole thing unwinds after the exception, it is freed it goes away and you don't need to free it.
