### ISSUE TITLE
Don't use a global geos context handle

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#31]
Currently a global handle is defined:

https://github.com/caspervdw/pygeos/blob/de5ed5c5f0a55bf471531e328d1a1b0476bcafd2/src/ufuncs.c#L1206-L1211

However, if you want to use pygeos in multiple threads (when releasing the GIL, https://github.com/caspervdw/pygeos/issues/7), I *think* we need a context per thread.

In the cython branch of geopandas, we had a context manager to create and destroy a thread:

https://github.com/geopandas/geopandas/blob/e92536340fd7f1ed92925b960226ab10adb37717/geopandas/vectorized.pyx#L1270-L1278

which was then used in each vectorized function (here the ufuncs) around the code that called into GEOS.

I suppose we will need something similar here, although not sure what the best way would be (since the ufuncs are templated, just creating in the beginning / destroying at the end might be not too much duplication). 

The version in pygeos also sets the error message handler, which we didn't do in the cython version. Is that for converting geos errors into python errors? (and does that work how it is currently coded? Shapely wraps some logging functionality with it)

**Comment by caspervdw** [comment]
I actually had this in the ufuncs before. It's not so much extra boilerplate, but I was worried about the additional overhead it would create. Are you sure you need a context per thread? Or is the context already a thread-safe way to storing global variables?

> The version in pygeos also sets the error message handler, which we didn't do in the cython version. Is that for converting geos errors into python errors? (and does that work how it is currently coded? Shapely wraps some logging functionality with it)

Yes I pack the GEOS error message into a python GEOSException. For example, if you try to get the `pygeos.boundary` of a geometrycollection. That should probably also be changed when we want to release the GIL..

**Comment by jorisvandenbossche** [comment]
Hmm, I don't directly find any discussion about this (and also not directly any GEOS docs on this), but for some reason I thought this was the motivation for changing that in the geopandas-cython branch (we initially had a global context as well).

**Comment by jorisvandenbossche** [comment]
I found an example in the GEOS source (https://github.com/libgeos/geos/blob/master/tests/thread/threadtest.c), which initializes a handle in each thread. And from https://trac.osgeo.org/geos/wiki/RFC3 I seem to understand the same (I understand it as the handle being a way to store global variables in a thread-safe way, as through the per-context handle, each thread has its copy of the global variables; "allowing each thread to have it's own copy of the data" from the document).


We should probably do some timings to check the overhead of creating a context on each function call.
