### ISSUE TITLE
Error when Shapely and pygeos are installed alongside in Windows

### ISSUE THREAD

**Issue by abey79** [pygeos/pygeos#311]
I have a project where both Shapely and PyGEOS are used and I does't work on Windows due to DLL loading issues. I'm assuming that this is due to `goes.dll` being present in both packages.

Is PyGEOS meant to work alongside Shapely? If so, what is the proper way to install it on Windows?

Note: the same project works flawlessly on both Linux and macOS.

cc @LoicGoulefert

#### Reproducing

```
> python -m venv pygeos_venv

> pygeos_venv\Scripts\activate

(pygeos_venv) > pip install pygeos shapely
Collecting pygeos
  Using cached pygeos-0.9-cp38-cp38-win_amd64.whl (977 kB)
Collecting shapely
  Using cached Shapely-1.7.1-cp38-cp38-win_amd64.whl (1.0 MB)
Collecting numpy>=1.13
  Using cached numpy-1.20.1-cp38-cp38-win_amd64.whl (13.7 MB)
Installing collected packages: numpy, pygeos, shapely
Successfully installed numpy-1.20.1 pygeos-0.9 shapely-1.7.1
WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\users\hhip\desktop\pygeos_venv\scripts\python.exe -m pip install --upgrade pip' command.

(pygeos_venv) > python -c "import shapely.ops; import pygeos"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hhip\Desktop\pygeos_venv\lib\site-packages\pygeos\__init__.py", line 1, in <module>
    from .lib import GEOSException  # NOQA
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

(pygeos_venv) > python -c "import pygeos; import shapely.ops"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hhip\Desktop\pygeos_venv\lib\site-packages\shapely\ops.py", line 13, in <module>
    from shapely.prepared import prep
  File "C:\Users\hhip\Desktop\pygeos_venv\lib\site-packages\shapely\prepared.py", line 5, in <module>
    from shapely.geos import lgeos
  File "C:\Users\hhip\Desktop\pygeos_venv\lib\site-packages\shapely\geos.py", line 169, in <module>
    _lgeos = load_dll("geos_c.dll")
  File "C:\Users\hhip\Desktop\pygeos_venv\lib\site-packages\shapely\geos.py", line 60, in load_dll
    raise OSError(
OSError: Could not find lib geos_c.dll or load any of its variants [].
```

The second case (`python -c "import pygeos; import shapely.ops"`) also yield to this error:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/49431240/110249003-1b8b9b00-7f74-11eb-83c7-61e1e7dcb873.png">

#### Environment

Windows 10 (actually running in a Parallels Desktop VM)
Python 3.8.6 (official installer)

**Comment by caspervdw** [comment]
Hi @abey79,
It seems that you are indeed looking at incompatibilities between the packaged binaries (`geos_c.dll`) of pygeos and shapely.
I do not see any easy way of solving this issue, so I'd recommend first looking into installation using conda.

If that is not an option, then you should build from source, which involves setting up the correct VS C++ compiler and downloading GEOS yourself.

**Comment by caspervdw** [comment]
These packaging issues will solve itself as soon as we merge with shapely. So closing this one.
