### ISSUE TITLE
GEOS errors decoding WKB prevent reading from datasets with invalid geometries

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#320]
Various tools are using WKB as a serialization format or transport format between different binary packages (e.g., reading from GDAL as WKB, then converting to geometries here).  The same is probably true for WKT.

If any of the WKB geometries are malformed, GEOS throws an error and the entire conversion fails.  This makes it challenging to work with 3rd-party datasets that have invalid geometries, since these first need to be converted to geometries before they can be filtered.

We can potentially get around this in one of 2 ways:
1. add a parameter to `from_wkb` that would allow invalid geometries to be returned as `None`, and raise a warning
2. always return invalid geometries as `None` and raise a warning.  This is simpler and the only API change is that it doesn't fail outright (which is likely undesirable here).

The user can then filter out the `None` geometries and continue with the remainder.

To be clear: for other areas where the user can actually control how geometries are constructed, it is totally appropriate to raise an exception.  It is only in cases of deserializing WKB / WKT that it would be better to gracefully handle such errors.

**Comment by jorisvandenbossche** [comment]
Some equivalent pandas functions that parse eg text input to numbers / datetimes (`to_numeric`, `to_datetime`), have a similar concept of "coercing" invalid input to NaN, that has certainly be useful from time to time for similar reasons as you describe above. 

I think a keyword would be good, so the default to raise an error is preserved.
