### ISSUE TITLE
Memory limits

### ISSUE THREAD

**Issue by 0phoff** [pygeos/pygeos#332]
I have been getting issues with PyGEOS happily hogging all my RAM, to the point where my computer stalls.
I would have expexted it to return some kind of MemoryError, but everything simply seems to freeze.
(Note that I have no swap, so it cannot be that it uses my swap memory).

Here is a (contrived) example that makes it happen.
Note that I had to enter a "ridiculous amount" of boxes, but it actually happened on one of my real scenarios, where other pieces of my code already allocate RAM and thus the number of boxes to make my system crash, are lower.
```python
import pygeos

b1 = pygeos.box(0,0,1,range(1,5001))   # 5000 boxes
b2 = pygeos.box(0,0,1,range(1,75001))  # 75000 boxes
inter = pygeos.area(pygeos.intersection(b1[:, None], b2[None, :]))
```

I do not know whether it is possible to set some kind of limit on the amount of RAM geos can allocate, and return a MemoryError if we go above ? Maybe something with a context manager ? I am really out of my depths here, so I am not at all sure this is actually possible. I just know that GDAL has a GDAL_CACHEMAX variable, but I don't know whether something similar can be used for Geos.
It would just be nice if my python program simply crashed, instead of halting my entire computer...

In the meantime, I will split my huge list of polygons, and compute the area in multiple passes.
I just need to find the right amount of polygons that I can safely use, which is highly dependant on the system... :confetti_ball: 

---

However, there could potentially be another solution:

As you can see in the example above, I compute the intersection polygons and then use those to compute an area.
I believe the system could use much less memory, if we would have a function to compute the intersection area straight away, and thus would not need to store the intermediate polygons.
Obviously, the exact same case could be made for all of the unary predicate methods and it would be unwieldy to create separate functions for all combinations of `[intersection, union, difference, ...]` and `[area, has_z, is_ccw, is_empty, ...]`.  

Would it be possible to somehow add an argument to the intersection function, which should be a string with the name of one of those unary predicate functions and run those in the same loop ?
Or maybe have a separate function that applies the pygeos functions one after the other, but in the same loop and only stores the final output ?
```python
# Idea 1
# Add a "predicate" arg to intersection, union, etc.
res = pygeos.intersection(b1, b2, predicate='area')

# Idea 2
# Create an extra "func_sequence" that runs functions one after the other in the same loop.
# This could be extended to mix different binary and unary functions,
# as a user could just add enough np.ndarrays in the final list arguments.
# We then perform some kind of reduction on the list.

# Run intersection on b1 and b2, then area on the result
res = pygeos.func_sequence('intersection', 'area', [b1, b2])

# Run intersection on b1 and b2, then union on that result and b3, finally area on the result
res = pygeos.func_sequence('intersection', 'union', 'area', [b1, b2, b3])
```

I might try and look into this, but I don't really have any experience with CPython / NumPy Ufuncs, so a few pointers might be nice (as well as telling me if this idea is completely stupid and unfeasible).
If the second idea seems better, this might be easier to implement using cython, as we are more flexible to use python ``*args`` and ``**kwargs`` to process the arguments. However, I do not know what your stance is on cython for this library (saw a post discussing this somewhere) ?

**Comment by caspervdw** [comment]
I think we are looking at a fundamental issue with “array-based” computation libraries like numpy. There is really no way of inserting anything into the inner loop of a ufunc, a consequence is that you execute the functions over the complete array one after another.

What you are proposing is one combination, but this problem persists in all possible permutations of functions (including 3 or more operations).

To work with these large arrays, you might want to consider using *dask*. I think you should be able to map a pygeos function over chunks in a dask array.

**Comment by jorisvandenbossche** [comment]
> I do not know whether it is possible to set some kind of limit on the amount of RAM geos can allocate, and return a MemoryError if we go above ?

NumPy will sometimes raise a MemoryError if it knows in advance that the result of an operation won't be able to fit in RAM. For example:

```
In [14]: arr = np.random.randn(1_000_000)

In [15]: arr[:, None] + arr[None, :]
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-15-ab8bbaaa4c07> in <module>
----> 1 arr[:, None] + arr[None, :]

MemoryError: Unable to allocate array with shape (1000000, 1000000) and data type float64
```

So indeed, it could be nice if pygeos had similar functionality. However, a big problem is that the elements in pygeos are variable-sized (a single Geometry can in theory already be too large for memory). So pygeos can't cheaply check the size of the result before executing the operation. 

(it could check for a lower bound, e.g. the memory used by the python object, but not sure that would be useful enough for the added complexity)

**Comment by jorisvandenbossche** [comment]
> To work with these large arrays, you might want to consider using dask. I think you should be able to map a pygeos function over chunks in a dask array.

Indeed. See https://github.com/pygeos/pygeos/issues/166#issuecomment-669169451 for an example of using dask with arrays. For things that fit in DataFrames (your intersection example above is not such as case, I think), you can check out https://github.com/geopandas/dask-geopandas

**Comment by caspervdw** [comment]
@0phoff  I consider this issue closed. Please feel free to reopen if you need anything more input from us.
