### ISSUE TITLE
Release 0.10 (or 1.0?)

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#333]
We have reached the milestone 0.10, and I think it is good to release and make the new features available to our users.

Also I think we have reached a point with pygeos that we have a sufficiently stable API to warrant a 1.0 release and remove the “beta”warnings. We can do that now, for my part, but we can also wait a bit and plan it for the next release, or wait until we merge with shapel. What do you think about this @jorisvandenbossche @brendan-ward ?

**Comment by brendan-ward** [comment]
👍 on 0.10 once #314 is in.

I think we should wait until after merge with Shapely.  I think we're getting closer to a stable API, but just to be safe would be good to let it stabilize a bit longer just to be sure.

**Comment by caspervdw** [comment]
#314 is in, any objections on releasing 0.10? I'll release once I have :+1: from @jorisvandenbossche and @brendan-ward

**Comment by caspervdw** [comment]
Oops found one issue: https://github.com/pygeos/pygeos/issues/339

**Comment by jorisvandenbossche** [comment]
Doing a 0.10 release sounds good. 

I would maybe just like to take a quick look at the new geometry creation functionality before it's released (@caspervdw thanks a lot for all your work on that, and sorry for my non-responsiveness on those PRs ..), but I can commit to doing that this evening.

**Comment by jorisvandenbossche** [comment]
With one day of delay ;), I took a look today, and so my first impression: great addition! (thanks a lot for those PRs, and again sorry for not reviewing them in time). 

I have two main issues which I think would be best resolved before releasing:

- There seems to be a bug when passing arrays -> https://github.com/pygeos/pygeos/issues/343 (I have to dig into my pandas knowledge, I know there that we also struggle from time to time with read-only buffers in python and object type)
- I have one concern about the exact API, i.e. for `polygons(..)`, see my comment at the PR at https://github.com/pygeos/pygeos/pull/326#issuecomment-819603547

In addition, the `return_index` features don't cover the use case of https://github.com/pygeos/pygeos/issues/75 (as I initially hoped, and for which I have a custom cython algo at https://github.com/pygeos/pygeos/pull/93. Reasons for this are 1) the exact indices needed are different and 2) doing it in a single pass (without needing to create intermediate Geometry objects) is still much faster. 
But I will comment about this in more detail at the related issues.

**Comment by caspervdw** [comment]
We are ready for the release! Please tell me if there are objections otherwise I'll start the release this afternoon.

**Comment by caspervdw** [comment]
Discussed with @jorisvandenbossche , it is time to release.

**Comment by caspervdw** [comment]
The source distribution is on Github and PyPI. Wheels are now being built for the test: https://github.com/pygeos/pygeos-wheels/pull/9 . And for conda-forge, I'll wait for the autotick-bot.

**Comment by caspervdw** [comment]
Wheels and conda-forge builds are out. So this can be closed.

**Comment by jorisvandenbossche** [comment]
Thanks for the release! This is a nice one ;)
