### ISSUE TITLE
WKB representation of empty 3D Point is 2-dimensional

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#336]
I am a bit lost in the previous discussions we had about this topic of WKB and empty points (and GEOS version dependencies .. etc), but noticed the following difference between Shapely and PyGEOS while running the Shapely tests (in the shapely-2.0 branch) with the latest pygeos:

```
>>> pygeos.to_wkb(pygeos.from_wkt("POINT Z EMPTY"), hex=True)
'0101000000000000000000F87F000000000000F87F'
```

This in contrast to Shapely (using the same GEOS 3.9.1 version):

```
>>> from shapely import wkt

>>> wkt.loads("POINT Z EMPTY").wkb_hex
'0101000080000000000000F87F000000000000F87F000000000000F87F'
```

**Comment by caspervdw** [comment]
The problem seems in the construction of the point:

```
In [1]: import pygeos
In [2]: pygeos.Geometry("POINT Z EMPTY")
Out[2]: <pygeos.Geometry POINT EMPTY>
In [3]: pygeos.from_wkt("POINT Z EMPTY")
Out[3]: <pygeos.Geometry POINT EMPTY>
In [4]: pygeos.from_wkb("0101000080000000000000F87F000000000000F87F000000000000F87F")
Out[4]: <pygeos.Geometry POINT EMPTY>
In [5]: from shapely import wkt
In [6]: pygeos.from_shapely(wkt.loads("POINT Z EMPTY"))
Out[6]: <pygeos.Geometry POINT EMPTY>
```

Looking at the tests, this issue appeared only since GEOS 3.8.0. I can't find any reason why shapely would be able to read 3D empty points and why pygeos is not...

**Comment by jorisvandenbossche** [comment]
On the other hand, when checking the coordinate dimension, the _construction_ actually seems to have catched that it is 3D:

```
In [56]: pygeos.get_coordinate_dimension(pygeos.Geometry("POINT Z EMPTY"))
Out[56]: 3

In [57]: pygeos.get_coordinate_dimension(pygeos.Geometry("POINT EMPTY"))
Out[57]: 2
```

So it might also be an issue in the conversion to WKB/WKT. Although for WKT, I don't see anything obvious differently in the settings of the WKTWriter (3D is enabled in both, and for non-empty it's also working correctly).

**Comment by jorisvandenbossche** [comment]
We do have a bunch of special code to handle the empty points in geometries for WKB conversion in pygeos, though, so a difference might be coming from there. And putting some debug print statements in `point_empty_to_nan`, it seems that this is correctly getting a 3D point, it's creating a CoordSeq with 3 NaNs, but when then creating a Point of this CoordSeq with `GEOSGeom_createPoint_r`, that gives a "2 dimensional" point ..

```
In [2]: pygeos.to_wkb(pygeos.from_wkt("POINT Z EMPTY"))
Inside point_empty_to_nan
-- Coord dimension of input: 3 
-- Setting NaN
-- Setting NaN
-- Setting NaN
-- Coord dimension of result: 2 
Out[2]: b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf8\x7f\x00\x00\x00\x00\x00\x00\xf8\x7f'
```

<details>
<summary>With this patch </summary>

```diff
--- a/src/geos.c
+++ b/src/geos.c
@@ -6,6 +6,7 @@
 #include <Python.h>
 #include <numpy/npy_math.h>
 #include <structmember.h>
+#include <stdio.h>
 
 /* This initializes a globally accessible GEOSException object */
 PyObject* geos_exception[1] = {NULL};
@@ -122,8 +123,10 @@ GEOSGeometry* point_empty_to_nan(GEOSContextHandle_t ctx, GEOSGeometry* geom) {
   int j, ndim;
   GEOSCoordSequence* coord_seq;
   GEOSGeometry* result;
+  printf("Inside point_empty_to_nan\n");
 
   ndim = GEOSGeom_getCoordinateDimension_r(ctx, geom);
+  printf("-- Coord dimension of input: %d \n", ndim);
   if (ndim == 0) {
     return NULL;
   }
@@ -133,6 +136,7 @@ GEOSGeometry* point_empty_to_nan(GEOSContextHandle_t ctx, GEOSGeometry* geom) {
     return NULL;
   }
   for (j = 0; j < ndim; j++) {
+    printf("-- Setting NaN\n");
     if (!GEOSCoordSeq_setOrdinate_r(ctx, coord_seq, 0, j, Py_NAN)) {
       GEOSCoordSeq_destroy_r(ctx, coord_seq);
       return NULL;
@@ -143,6 +147,8 @@ GEOSGeometry* point_empty_to_nan(GEOSContextHandle_t ctx, GEOSGeometry* geom) {
     GEOSCoordSeq_destroy_r(ctx, coord_seq);
     return NULL;
   }
+  ndim = GEOSGeom_getCoordinateDimension_r(ctx, result);
+  printf("-- Coord dimension of result: %d \n", ndim);
   GEOSSetSRID_r(ctx, result, GEOSGetSRID_r(ctx, geom));
   return result;
 }
```

</details>

So it's `GEOSGeom_createPoint_r` that is buggy (or has unexpected behaviour).

**Comment by jorisvandenbossche** [comment]
Looking a bit at the GEOS code, it might be that `GEOSGeom_createPoint_r` is actually fine, but that a point with a NaN z-value is considered as 2D .. See eg https://github.com/libgeos/geos/blob/921f88d1e829f8114c2ff1ccd4fa7858960e880f/include/geos/geom/FixedSizeCoordinateSequence.h#L84-L101 
Which would mean that our trick of using points with all-NaN doesn't work for 3D empty points (or at least not for empty Point, didn't check what it gives with empty points in MultiPoint/GeometryCollection). 

And given that Shapely does the correct thing, it seems that for "POINT Z EMPTY", GEOS actually already does the correct thing itself for GEOS 3.9 (while in our code we only leave out our custom handling starting with GEOS 3.10. That might be for also handling the MultiPoint / GeometryCollection cases?)

**Comment by caspervdw** [comment]
> On the other hand, when checking the coordinate dimension, the _construction_ actually seems to have catched that it is 3D:
> 
> ```
> In [56]: pygeos.get_coordinate_dimension(pygeos.Geometry("POINT Z EMPTY"))
> Out[56]: 3
> 
> In [57]: pygeos.get_coordinate_dimension(pygeos.Geometry("POINT EMPTY"))
> Out[57]: 2
> ```
> 
> So it might also be an issue in the conversion to WKB/WKT. Although for WKT, I don't see anything obvious differently in the settings of the WKTWriter (3D is enabled in both, and for non-empty it's also working correctly).

So I do get these results:

```
>>> pygeos.has_z(pygeos.Geometry("POINT Z EMPTY"))
False
>>> pygeos.to_wkt(pygeos.Geometry("POINT Z EMPTY"))
"POINT EMPTY"
```

Which surprise me because we do not do any special stuff in the WKT writer.

**Comment by jorisvandenbossche** [comment]
Yes, but at least that's the same in Shapely, so that might also be a limitation/bug of GEOS:

```python
In [4]: wkt.loads("POINT Z EMPTY").wkt
Out[4]: 'POINT EMPTY'
```

**Comment by caspervdw** [comment]
> Yes, but at least that's the same in Shapely, so that might also be a limitation/bug of GEOS:
> 
> ```python
> In [4]: wkt.loads("POINT Z EMPTY").wkt
> Out[4]: 'POINT EMPTY'
> ```

I created a ticket at GEOS: https://trac.osgeo.org/geos/ticket/1129
