### ISSUE TITLE
Consider LinearRing as "closed"?

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#337]
I didn't directly find a previous discussion about this, but currently the `is_closed` ufunc will always return False for LinearRings:

```python
>>> ring = pygeos.linearrings(((0, 0), (0, 1), (1 ,1 ), (1, 0)))
>>> print(ring)
LINEARRING (0 0, 0 1, 1 1, 1 0, 0 0)
>>> pygeos.is_closed(ring)
False
```

This is following GEOS' behaviour where `GEOSisClosed` only works for LineStrings and not any other geometry (and thus also not LinearRings). 

However, in Shapely, a LinearRing is also considered as "closed" (by simply hardcoded always True for a LinearRing):

```python
>>> from shapely.geometry import LinearRing
>>> ring = LinearRing( ((0, 0), (0, 1), (1 ,1 ), (1, 0)))
>>> print(ring)
LINEARRING (0 0, 0 1, 1 1, 1 0, 0 0)
>>> ring.is_closed
True
```

PostGIS (https://postgis.net/docs/ST_IsClosed.html) seems to return True as well. It's not directly documented, but from a quick test (creating a polygon and extracting the exterior ring, as creating the LinearRing from WKT doesn't seem to be supported):

```
test_db=# SELECT ST_IsClosed(ST_ExteriorRing('POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))'::geometry));
 st_isclosed 
-------------
 t
(1 row)
```

Although PostGIS also returns True for Polygon

**Comment by brendan-ward** [comment]
Interesting that GEOS is limited to LineString / MultiLineString and rejects all other types, rather than also accepting LinearRings / Polygons / MultiPolygons and always returning true.

Since by definition LinearRings are always closed (or they cannot be constructed), we should probably always return True where type ID is 2,3,6.  For GeometryCollection, should this recurse and return True if True for all geometries within it, or just always return False as now (but note maybe in docstring that is the case and that operating on component geometries may return real result).

It looks like we are conflating what `GEOSisClosed_r` can be called with vs what is True by definition of types (i.e., you shouldn't need to call GEOS at all if not LineString / MultiLineString); handling this in `GEOSisClosedAllTypes_r` for the above types semes like the right thing to do.

**Comment by jorisvandenbossche** [comment]
There was some related discussion about this on the GEOS chat channel (https://matrix.to/#/!STHkqHfzeJCHESrcdy:matrix.org/$1611003451283059XDGhx:matrix.org?via=matrix.org&via=gitter.im&via=osgeo.org) about `isRing` and `isSimple`, which have similarly strange behaviour for rings

**Comment by brendan-ward** [comment]
I think those are separate issues around validity (in the geometric sense), etc.  I haven't seen anything that lets us construct a LinearRing or a polygon with LinearRings that don't satisfy that condition (either closing coordinate is automatically added or an exception is raised).

The [implementation](https://github.com/libgeos/geos/blob/3.9/src/geom/LineString.cpp#L196-L203) just compares first and last coordinates, so I think we can sidestep any issues around simplicity, geometric validity, etc.  Though I'm not sure why casting a LinearRing to a LineString (in the C API) would create something that doesn't meet that condition.  But we aren't exercising that, we're never even calling the C API if not a LineString / MultiLineString.

**Comment by jorisvandenbossche** [comment]
It was mentioned in that thread that you *can* construct (with the GEOS C++ APIs, I suppose) a LinearRing that is not a valid LinearRing, but I suppose this is about the "is simple" constraint, and not about the "is closed" constraint (since that gets validated upon construction: https://github.com/libgeos/geos/blob/13abebc94abe7b269104e85ba57181bbc17911b8/src/geom/LinearRing.cpp#L56-L74)

In that case, yes, then for "is_closed" it's simpler and we can always assume a LinearRing to be closed. 

The question is still if you want to return True for non-lineal geometries as well like polygons. Eg for "is_ring" in geopandas, we always returned True for Polygons, but decided to deprecate that (can of course still be re-considered)

**Comment by brendan-ward** [comment]
I guess the question is whether or not `is_closed` should be semantically equivalent to `is_ring`: i.e., can a Polygon be considered "closed" but not a ring?  A polygon isn't a ring, it _has_ a ring, but definitions of Polygons describe them as "closed" figures (e.g., `a closed plane figure bounded by straight lines`).
