### ISSUE TITLE
BUG? polygons(..) with indices gives "buffer source array is read-only" error

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#343]
Assume I have an array of rings, and an array of indices mapping each ring to the polygon they belong:

```python
import pygeos

# 1D array of rings with shape (10, )
rings = pygeos.linearrings(np.random.randn(10, 3, 2))
polygon_indices = np.array([0,1,1,2,2,2,3,4,4,5])
```

with some manipulation of the indices, I can get split the rings into shells and holes, and get the hole indices:

```python
polygon_indices_shell = np.insert(np.diff(polygon_indices), 0, 1)
shells_mask = polygon_indices == 1
holes_mask = polygon_indices == 0

shells = rings[shells_mask].copy()
holes = rings[holes_mask].copy()
hole_indices = polygon_indices[holes_mask].copy()
```

but passing those arguments (I even added `copy()` to be sure) gives the following error:
```
In [5]: pygeos.polygons(shells, holes, indices=hole_indices)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-76bad8a0d07f> in <module>
----> 1 pygeos.polygons(rings[shells_mask].copy(), rings[holes_mask].copy(), indices=polygon_indices[holes_mask].copy())

~/scipy/repos/pygeos/pygeos/decorators.py in wrapped(*args, **kwargs)
     54             for arr in array_args:
     55                 arr.flags.writeable = False
---> 56             return func(*args, **kwargs)
     57         finally:
     58             for arr, old_flag in zip(array_args, old_flags):

~/scipy/repos/pygeos/pygeos/creation.py in polygons(shells, holes, indices, **kwargs)
    164         return lib.polygons(shells, holes, **kwargs)
    165     else:
--> 166         return polygons_1d(shells, holes, indices)
    167 
    168 

~/scipy/repos/pygeos/pygeos/_geometry.pyx in pygeos._geometry.polygons_1d()

~/scipy/repos/pygeos/pygeos/_geometry.cpython-38-x86_64-linux-gnu.so in View.MemoryView.memoryview_cwrapper()

~/scipy/repos/pygeos/pygeos/_geometry.cpython-38-x86_64-linux-gnu.so in View.MemoryView.memoryview.__cinit__()

ValueError: buffer source array is read-only
```

Is there something that I am missing that I am doing wrong?

**Comment by jorisvandenbossche** [comment]
So passing the rings (shells and holes) as a list works (`pygeos.polygons(list(shells), list(holes), indices=hole_indices)`)

**Comment by caspervdw** [comment]
Funny that this never popped up when I was working on it. Good catch.

This is related to https://github.com/cython/cython/issues/1605 : typed memory views and readonly arrays are incompatibly. So as long as we do not release the GIL in the Cython functions (ref #226) we should be fine with using the `multithreading_enabled` decorators for the ufuncs only.

**Comment by jorisvandenbossche** [comment]
Ah, I forgot about the decorator that makes them readonly ..  (because I explicitly checked and copies my arrays that they were certainly not read-only ;))

Now, the issue you mention is fixed in the meantime, in general you can work with `const` memoryviews to support read-only arrays. But, `const` is not supported for `object` type (https://github.com/cython/cython/issues/2485), so that doesn't help here. 
This is the reason that in pandas we don't use memoryviews but use the older np.ndarray cython interface whenever a function needs to support object type.

**Comment by jorisvandenbossche** [comment]
So this patch also works, and will then also work if the user, for some reason, passes a read-only array:

```diff
--- a/pygeos/_geometry.pyx
+++ b/pygeos/_geometry.pyx
@@ -410,7 +410,7 @@ def collections_1d(object geometries, object indices, int geometry_type = 7):
 
 @cython.boundscheck(False)
 @cython.wraparound(False)
-def polygons_1d(object shells, object holes, object indices):
+def polygons_1d(np.ndarray[object, ndim=1] shells, np.ndarray[object, ndim=1] holes, object indices):
     cdef Py_ssize_t hole_idx_1 = 0
     cdef Py_ssize_t poly_idx = 0
     cdef unsigned int n_holes = 0
@@ -421,12 +421,10 @@ def polygons_1d(object shells, object holes, object indices):
     cdef GEOSGeometry *poly = NULL
 
     # Cast input arrays and define memoryviews for later usage
-    shells = np.asarray(shells, dtype=object)
     if shells.ndim != 1:
         raise TypeError("shells is not a one-dimensional array.")
 
     # Cast input arrays and define memoryviews for later usage
-    holes = np.asarray(holes, dtype=object)
     if holes.ndim != 1:
         raise TypeError("holes is not a one-dimensional array.")
 
@@ -448,8 +446,6 @@ def polygons_1d(object shells, object holes, object indices):
         raise ValueError("The indices should be sorted.")  
 
     cdef Py_ssize_t n_poly = shells.shape[0]
-    cdef object[:] shells_view = shells
-    cdef object[:] holes_view = holes
     cdef int[:] indices_view = indices
 
     # get the holes count per polygon (this raises on negative indices)
@@ -469,7 +465,7 @@ def polygons_1d(object shells, object holes, object indices):
             n_holes = 0
 
             # get the shell
-            if PyGEOS_GetGEOSGeometry(<PyObject *>shells_view[poly_idx], &shell) == 0:
+            if PyGEOS_GetGEOSGeometry(<PyObject *>shells[poly_idx], &shell) == 0:
                 raise TypeError(
                     "One of the arguments is of incorrect type. Please provide only Geometry objects."
                 )
@@ -490,7 +486,7 @@ def polygons_1d(object shells, object holes, object indices):
 
             # fill the temporary array with holes belonging to this polygon
             for poly_hole_idx in range(hole_count[poly_idx]):
-                if PyGEOS_GetGEOSGeometry(<PyObject *>holes_view[hole_idx_1 + poly_hole_idx], &hole) == 0:
+                if PyGEOS_GetGEOSGeometry(<PyObject *>holes[hole_idx_1 + poly_hole_idx], &hole) == 0:
                     _deallocate_arr(geos_handle, temp_holes_view, n_holes)
                     raise TypeError(
                         "One of the arguments is of incorrect type. Please provide only Geometry objects."
```

**Comment by caspervdw** [comment]
Why then would you work with typed memoryviews?

I am curious if the C-compiled version now does an INCREF / DECREF (as was done with the memoryviews). That is hindering the GIL release.

**Comment by jorisvandenbossche** [comment]
> Why then would you work with typed memoryviews?

Compared to the cython numpy interface, typed memorviews are newer, and are generally seen as 1) slightly faster 2) nicer to use (and also support any object with the buffer interface, and not just numpy arrays, although that's not very relevant for us, I think). 

See https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html, which says "Memoryviews are similar to the current NumPy array buffer support (`np.ndarray[np.float64_t, ndim=2]`), but they have more features and cleaner syntax."

> I am curious if the C-compiled version now does an INCREF / DECREF (as was done with the memoryviews). That is hindering the GIL release.

I would need to look at the generated source, but I assume that will be the same yes. 
See also https://github.com/pygeos/pygeos/issues/226 and the linked notebook in the top post. That has a small reproducer for cython, uses the numpy buffer protocol and also has INCREF/DECREF when accessing an element of the array (the annotated code has the generated C code as well, if you expand a line).

**Comment by jorisvandenbossche** [comment]
> Why then would you work with typed memoryviews?

And note that this limitation of not working with read-only arrays is only for object-dtype arrays. When you write algorithms in cython for numeric arrays, you don't have such issues, and memoryviews work nicely.
