### ISSUE TITLE
Voronoi Polygons Need to Reference Original Points

### ISSUE THREAD

**Issue by zegres** [pygeos/pygeos#344]
It would be very useful to optionally return a mapping between the coordinates passed to voronoi_polygons function and the resulting polygons.

**Comment by jorisvandenbossche** [comment]
@zegres thanks for the suggestion. We are dependent here on the underlying GEOS library that implements the algorithm. It accepts any geometry (and uses the vertices, so points, of that geometry) and returns a collection of polygons. But I don't know if there is any guarantee about the order of the returned polygons, which would the only way to know the mapping (apart from calculating it afterwards with a spatial join).

**Comment by jorisvandenbossche** [comment]
And based on a quick test, there doesn't seem to be a corresponding order:

```
mp = pygeos.multipoints(np.random.randn(10,2))
points = pygeos.get_parts(mp)
polygons = pygeos.get_parts(pygeos.voronoi_polygons(mp))

ax = geopandas.GeoSeries(polygons).plot(cmap="viridis")
geopandas.GeoSeries(points).buffer(0.1).plot(cmap="viridis", ax=ax, edgecolor="k")
```

gives

![Figure_1](https://user-images.githubusercontent.com/1020496/115107830-777f1180-9f6d-11eb-9078-de22290b5200.png)

**Comment by caspervdw** [comment]
I'm closing this as we can't do anything about it in PyGEOS. Please feel free to open a GEOS ticket @zegres
