### ISSUE TITLE
Remove method of STRtree

### ISSUE THREAD

**Issue by Saelyos** [pygeos/pygeos#356]
In GEOS there are two methods `STRtree::insert` and `STRtree::remove` that are not currently implemented in `pygeos`. I would be really interested in having the `remove` method available.

In strtree.c / strtree.h, I see that `_geos` accepts  `NULL` variables, so it should be possible to call `STRtree::remove` and make `NULL` the corresponding removed objects in `_geos` (to know what the indices of those objects are, it may be needed to have an intersects query - as it is done internally in GEOS).

I can try to make a PR if you want, but I'm not sure of its feasibility as I don't know all the code details.

**Comment by jorisvandenbossche** [comment]
I am not that familiar with the STRtree internals, but the doc comments says:

```
 * A query-only R-tree created using the Sort-Tile-Recursive (STR) algorithm.
 * For two-dimensional spatial data.
 *
 * The STR packed R-tree is simple to implement and maximizes space
 * utilization; that is, as many leaves as possible are filled to capacity.
 * Overlap between nodes is far less than in a basic R-tree. However, once the
 * tree has been built (explicitly or on the first call to #query), items may
 * not be added or removed.
```

So if that's correct, a `remove` method would only be useful directly after creating the tree. But in such a case you could also create the tree with a subset of the geometries to start with?

**Comment by Saelyos** [comment]
I am not familiar with it either, and had actually missed this comment. However the doc doesn't seem to agree with the code : while you can't apparently `insert` after the tree has been built : 
```c++
void
AbstractSTRtree::insert(const void* bounds, void* item)
{
    // Cannot insert items into an STR packed R-tree after it has been built
    assert(!built);
    itemBoundables->push_back(new ItemBoundable(bounds, item));
}
```
That doesn't seem to be the case for `remove`, the tree being actually built first : 
``` c++
bool
AbstractSTRtree::remove(const void* searchBounds, void* item)
{
    if(!built) {
        build();
    }
    if(itemBoundables->empty()) {
        assert(root->getBounds() == nullptr);
    }
    if(getIntersectsOp()->intersects(root->getBounds(), searchBounds)) {
        return remove(searchBounds, *root, item);
    }
    return false;
}
```

**Comment by Saelyos** [comment]
So do you think a `remove` implementation could be possible in pygeos ?

**Comment by brendan-ward** [comment]
I think we'd need to do more digging into how this would be handled in GEOS, given the disparity between the docstring and the implementation.

As for pygeos, we make assumptions that the tree is immutable (e.g., using pointer addresses in the original array to determine indexes in the tree items during `query`, etc).

Can you tell us more about your use case of why you need the remove functionality after the tree is built, and why that is necessary rather than building a new immutable tree after a change to the data to be indexed?

**Comment by Saelyos** [comment]
Basically my use case can be described as follow:
- Take the closest point in the tree from another point A.
- Do some stuff with this closest point (such as computing the coordinates of point B)
- Remove that closest point from the tree.
- Take the closest point in the tree from point B.
- Do some stuff with this closest point (such as computing the coordinates of point C)
- ...

Repeat until all the points have been removed from the tree. 

Performance wise, it wouldn't be acceptable to build a new immutable tree every time, whereas a remove should be fast.

**Comment by caspervdw** [comment]
I am closing this as this cannot be supported by PyGEOS due to lack of support in the GEOS C API.
