### ISSUE TITLE
STRTree nearest arguments of incorrect type

### ISSUE THREAD

**Issue by sblandin2018** [pygeos/pygeos#363]
Hello to everybody and thanks for the work on the module.

I am not directly using pyGEOS but I use a little module named [snkit](https://github.com/tomalrussell/snkit) to clean a messed up geographical network. snkit depends on geopandas to perform its operations.

I am using Anaconda on a 64 bit Windows 10 machine. pyGEOS version is 0.10, snkit is 1.6.0 and geopandas is version 0.9.0.

When I enable pyGEOS support I get an error on the `nearest` method of the `STRtree` class. The full error message is:

> One of the arguments is of incorrect type. Please provide only Geometry objects.

The error happens on line 225 of the `strtree` module on the following code:

`return self._tree.nearest(geometry) `

I do not understand why I am getting this error. According to the docstring you can pass `Geometry` or `array_like` object as `geometry` argument of `nearest`.

snkit invokes `nearest` in the following way:

```
"""Find the element of a GeoDataFrame nearest a shapely geometry
"""
matches_idx = gdf.sindex.nearest(geom.bounds)
```

where `geom` argument is a `Point` geometry. 

Shouldn't `nearest` work when called this way?

**Comment by brendan-ward** [comment]
@sblandin2018 I don't think there is enough information here yet for us to diagnose this.  Can you share a small reproducible code example?

Are you calling the `STRtree` nearest function with pygeos geometry objects, or bounds like in your lower example?

Here's a little more of an example of what works:
```python
>>> tree = pygeos.STRtree(pygeos.points([0,0], [1,1]))
>>> tree.nearest(pygeos.points([0.25,0])
# array of one point
>>> tree.nearest(pygeos.points([0.25,0]))
array([[0],
       [0]])
# array of two points, constructed individually
>>> tree.nearest([pygeos.points(0.25,0), pygeos.points(0.5,0.75)])
array([[0, 1],
       [0, 0]])
```

See also: https://github.com/geopandas/geopandas/pull/1865 for how nearest is getting implemented as a spatial join in geopandas.

**Comment by sblandin2018** [comment]
Sorry for not providing a test case. I reproduced the error with the below code:

```
import geopandas as gpd
from shapely.geometry import Point

gpd.options.use_pygeos = True #if you set this to False you get the indexes

coords = zip(range(1, 10), range(1, 10))

gdf = gpd.GeoDataFrame(
    [Point(c) for c in coords],
    columns=['geometry'],
    geometry='geometry'
)

pt = Point([5, 6])

idx = gdf.sindex.nearest(pt.bounds) #With pygeos enabled this won't work even using pt
```

Executing the code you should get:

> TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-8-0d27cf235098> in <module>
>      14 pt = Point([5, 6])
>      15 
> ---> 16 idx = gdf.sindex.nearest(pt.bounds) #With pygeos enabled this won't work even using pt
>      17 
>      18 print(list(idx))
> 
> ~\AppData\Local\Continuum\anaconda3\envs\ultra-np\lib\site-packages\pygeos\strtree.py in nearest(self, geometry)
>     223             geometry = np.expand_dims(geometry, 0)
>     224 
> --> 225         return self._tree.nearest(geometry)
>     226 
>     227     @requires_geos("3.6.0")
> 
> TypeError: One of the arguments is of incorrect type. Please provide only Geometry objects.

As I said, I do not use pygeos directly in my code but I use a module that depends on geopandas. From the sample code you provided it seems that to make it work with pygeos enabled I need to explicitly pass a pygeos.points object.

**Comment by brendan-ward** [comment]
Yes, to use pygeos directly, you need to pass in pygeos geometries, not shapely geometries.  `gdf.sindex.nearest` is using the pygeos STRtree directly, so it expects pygeos geometries (note that `sindex.nearest` isn't really part of the geopandas public API).  You are passing in either Shapely geometries or a bounds array, so the error that you get from pygeos is expected; they are indeed not the correct type.  When you use this directly, geopandas doesn't do any automatic conversion of types for you.  The nearest spatial join implemented in geopandas (mentioned above) will do more of this conversion for you, between 2 GeoDataFrames.

If you have pygeos turned on for geopandas, as you do here, you can get at the pygeos geometries of a GeoDataFrame using `gdf.geometry.values.data`.

In this case, `pt` is a Shapely geometry. There are a few ways you could make it compatible:

```python
# use pygeos.from_shapely
p = pygeos.from_shapely(pt)

# construct directly as a pygeos geometry
p = pygeos.points(5,6)
```

Then once you have a pygeos geometry, you can use it against other pygeos operations like `nearest`:

```
>>> gdf.sindex.nearest(p)
array([[0],
       [4]])
```

Questions / comments about nearest neighbor operations in geopandas should be opened as issues in the geopandas repository; that is the correct place to highlight usability issues around type conversions when using geopandas.  Here in pygeos, things are working as expected.  I hope that helps!

**Comment by sblandin2018** [comment]
Thanks for the expalnation.
 
As I said, I do not use pygeos directly. Looking carefully to snkit issues it seems that the problem is known to the module maintainer: https://github.com/tomalrussell/snkit/issues/37#issue-827607701

I suppose we can close this issue

**Comment by martinfleis** [comment]
>  `sindex.nearest` isn't really part of the geopandas public API

But it should :). I'll open an issue in the GeoPandas repo.
