### ISSUE TITLE
import pygeos error

### ISSUE THREAD

**Issue by hengshan** [pygeos/pygeos#364]
hi, anyone can help with this? Thanks
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-021f8911880a> in <module>
----> 1 import pygeos

C:\OSGEO4~1\apps\Python37\lib\site-packages\pygeos\__init__.py in <module>
----> 1 from .lib import GEOSException  # NOQA
      2 from .lib import Geometry  # NOQA
      3 from .lib import geos_version, geos_version_string  # NOQA
      4 from .lib import geos_capi_version, geos_capi_version_string  # NOQA
      5 from .decorators import UnsupportedGEOSOperation  # NOQA

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by brendan-ward** [comment]
How did you install pygeos?  On Windows, installing via `conda` should work.

From first glance, it looks like there could be a mismatch against the version of GEOS that pygeos is pointing to, possibly due to installing from `pip install pygeos`?

**Comment by mwtoews** [comment]
It looks like you are running Python in an OSGeo4W shell, which does not currently have (e.g.) `python3-pygeos` available. You can try to install a binary wheels version via pip:

    python3 -m pip install -U pygeos

but admittedly this is a bit hackish, as I'm not aware how OSGeo4W folks fell about using pip, as it might (e.g.) install a different version of numpy and break things like gdal. A better strategy is to [open a ticket](https://trac.osgeo.org/osgeo4w/) to add support for pygeos.

**Comment by hengshan** [comment]
we are  using JupyterLab to develop standalone QGIS application under Windows (and Mac). OSGeo4W python -m pip works well for most packages such as geopandas and pysal on Mac . 

on Windows, however, installing geopandas raises errors. We have reinstalled  gdal, rasterio, fiona wheels version to solve the issue. The pygeos error happens when I was trying to import pysal.explore.  I temporarily solved this issue by: 
from .lib import *
# from .lib import GEOSException  # NOQA
# from .lib import Geometry  # NOQA
# from .lib import geos_version, geos_version_string  # NOQA
# from .lib import geos_capi_version, geos_capi_version_string  # NOQA

But another error of shapely pops up: Could not find lib geos_c.dll or load any of its variants [].... any ideas?

**Comment by mwtoews** [comment]
OSGeo4W has `python3-shapely` and `python3-geopandas` packages, so you shouldn't need to use pip. Another OSGeo4W resource is [here](https://trac.osgeo.org/osgeo4w/wiki/ExternalPythonPackages), although it looks a bit old.

A good alternative suggested by @brendan-ward is to build an environment with Miniconda (or Anaconda) containing PyGEOS, QGIS, JupyterLab, etc. for Windows/Mac/Linux. For instance https://anaconda.org/conda-forge/qgis looks promising.

    conda create -c conda-forge -n mystack qgis pygeos geopandas jupyterlab

**Comment by caspervdw** [comment]
Hi @hengshan , I am curious what distribution (wheel / python version) is downloaded when you call the “pip install pygeos”. Is it attempting to install from source or is it using a binary wheel?

Also could you print the contents of your PATH environment variable right at the first failing import? Pygeos is picky about the version of the geos_c.dll, so if another version of geos_c.dll would be earlier in the PATH, then I would expect errors like this.

**Comment by hengshan** [comment]
First, thanks @mwtoews @brendan-ward, conda indeed solves all the packages loading issues. works like a charm. 

however, I am still a little curious why OSGeo4W  pip has issues on Windows when loading packages such as pysal (requires shapely and pygeos).. the error is related to loading geos_c.dll. I found geos_c.dll at multiple locations: 

- C:\OSGeo4W64\bin\geos_c.dll, 
- C:\OSGeo4W64\apps\Python37\lib\site-packages\shapely\DLLs\geos_c.dll
- C:\OSGeo4W64\apps\Python37\lib\site-packages\pygeos\geos_c.dll
C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\geos_c.dll

Based on traceback, I dived a little deeper into the file: C:\OSGeo4W64\apps\Python37\lib\site-packages\shapely\geos.py
As shown in the following code, if it is conda, python uses C:\OSGeo4W64\bin\geos_c.dll. Otherwise, it seems quite confusing which dll it uses. I am quite new to the Python call DLL in windows. I wonder why shapely does this, and what these code mean. why not just use dll the package itself provides in the DLLs folder... 
 
```
elif sys.platform == 'win32':
    if os.getenv('CONDA_PREFIX', ''):
        # conda package.
        _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
    else:
        try:
            egg_dlls = os.path.abspath(
                os.path.join(os.path.dirname(__file__), 'DLLs'))
            if hasattr(sys, '_MEIPASS'):
                wininst_dlls = sys._MEIPASS
            elif hasattr(sys, "frozen"):
                wininst_dlls = os.path.normpath(
                    os.path.abspath(sys.executable + '../../DLLS'))
            else:
                wininst_dlls = os.path.abspath(os.__file__ + "../../../DLLs")
            original_path = os.environ['PATH']
            os.environ['PATH'] = "%s;%s;%s" % \
                (egg_dlls, wininst_dlls, original_path)
            _lgeos = load_dll("geos_c.dll")
        except (ImportError, WindowsError, OSError):
            raise

        def free(m):
            try:
                cdll.msvcrt.free(m)
            except WindowsError:
                # XXX: See http://trac.gispython.org/projects/PCL/ticket/149
                pass

def load_dll(libname, fallbacks=None, mode=DEFAULT_MODE):
    lib = find_library(libname)
    dll = None
    if lib is not None:
        try:
            LOG.debug("Trying `CDLL(%s)`", lib)
            dll = CDLL(lib, mode=mode)
        except OSError:
            LOG.debug("Failed `CDLL(%s)`", lib)
            pass

    if not dll and fallbacks is not None:
        for name in fallbacks:
            try:
                LOG.debug("Trying `CDLL(%s)`", name)
                dll = CDLL(name, mode=mode)
            except OSError:
                # move on to the next fallback
                LOG.debug("Failed `CDLL(%s)`", name)
                pass

    if dll:
        LOG.debug("Library path: %r", lib or name)
        LOG.debug("DLL: %r", dll)
        return dll
    else:
        # No shared library was loaded. Raise OSError.
        raise OSError(
            "Could not find lib {} or load any of its variants {}.".format(
                libname, fallbacks or []))
```

@caspervdw I run jupyter-lab using OSGeo4W Shell, and the path is as below.
`'C:\\OSGEO4~1\\apps\\Python37\\lib\\site\\packages;C:\\OSGEO4~1\\apps\\Python37\\lib;C:\\OSGEO4~1\\apps\\Python37\\DLLs;C:\\OSGEO4~1\\apps\\qgis\\python\\plugins;C:\\OSGEO4~1\\apps\\Python37\\Scripts;C:\\OSGEO4~1\\apps\\Python37;C:\\OSGEO4~1\\apps\\Qt5\\bin;C:\\OSGEO4~1\\apps\\qgis\\bin;C:\\OSGEO4~1\\apps\\qgis\\python;C:\\OSGEO4~1\\apps\\qgis\\bin;C:\\OSGEO4~1\\apps\\grass\\grass78\\lib;C:\\OSGEO4~1\\apps\\grass\\grass78\\bin;C:\\OSGEO4~1\\apps\\Python37;C:\\OSGEO4~1\\apps\\Python37\\Scripts;C:\\OSGEO4~1\\apps\\qt5\\bin;C:\\OSGEO4~1\\apps\\Python37;C:\\OSGEO4~1\\apps\\Python37\\Scripts;C:\\OSGEO4~1\\bin;C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\WBem;C:\\Program Files\\Git\\cmd;;C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\pywin32_system32;C:\\OSGEO4~1\\apps\\Python37\\lib\\site-packages\\pywin32_system32'`

**Comment by caspervdw** [comment]
Including DLL’s is a complex thing. There is a useful explanation over
here:
https://github.com/numpy/numpy/wiki/windows-dll-notes

The issue here is that windows finds the wrong version of geos_c.dll. One
way to fix this issue (for us) is making the included geos dllsuniquely
named before packaging them. Then windows will always find you the dll that
was distributed with pygeos.

See here for a tool:
https://pypi.org/project/delvewheel/

Op vr 25 jun. 2021 om 13:09 schreef Shan ***@***.***>

**Comment by hengshan** [comment]
@caspervdw Thanks. It is very useful. 

The issue is caused by the mismatch of geos_c dll. I am using OSGeo4W environment python, so the path contains: C:\OSGeo4W64\bin, 
In default, QGIS loads C:\OSGeo4W64\bin\geos_c.dll

When I import pygeos, it will check whether the same name dll has been loaded in the environment. As C:\OSGeo4W64\bin\geos_c.dll has been loaded, it will not search and load
C:\OSGeo4W64\apps\Python37\lib\site-packages\pygeos\geos_c.dll

I tried to change the dll name of QGIS geos_c.dll using dumpbin, but it is a bit hackish. wonder whether there is an easier way to change the name geos_c.dll in the pygeos package or QGIS.

Shapely has geos_c.dd but it works well, as it puts all dlls in a DLL folder and load it dynamically using the load_dll method (see above code). Pygeos, however, use "from .lib" to import. The issue is that if the same name of geos_c.dll has been loaded (QGIS loads it in default), it won't search for the dll in its own package.

**Comment by caspervdw** [comment]
@hengshan We managed to use a new tool to create wheels for windows. This tool mangles dll names so that there can't be a conflict with GEOS versions of different applications.

Would you care to try it out and report back if it works for you out of the box? 

Install the (alpha) version 0.10.2a2 as follows:
```
pip install --pre pygeos[test]
```

And then test it:
```
pytest --pyargs pygeos.tests
```

Fingers crossed!

**Comment by caspervdw** [comment]
Ref. #377

**Comment by caspervdw** [comment]
I am closing this because as of 0.10.2, the issue should be fixed. @hengshan Please feel free to reopen this if you encounter the issue again.
