### ISSUE TITLE
Issue installing PyGEOS on windows with Python 3.8+

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#383]
I encountered this issue in #382 . For some reason I am getting this when importing `pygeos`:

```
 Traceback:
c:\hostedtoolcache\windows\python\3.8.10\x64\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pygeos\__init__.py:1: in <module>
    from .lib import GEOSException  # NOQA
E   ImportError: DLL load failed while importing lib: The specified module could not be found.
```
Complete log: https://github.com/caspervdw/pygeos/runs/3455987095

This happens with any GEOS version, on Python 3.8 and 3.9 only. First I thought it was an issue with setuptools, but I can reproduce it locally (using OSGeo4W build of GEOS) with setuptools 47, 49, 56, and 57 (latest). One question here is: why does Appveyor work? Do you have any ideas @mwtoews ?

With a Dependency checker (This one: https://github.com/lucasg/Dependencies) I cannot find any broken dependency locally.

**Comment by caspervdw** [comment]
This may be the cause:

> DLL dependencies for extension modules and DLLs loaded with ctypes on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with add_dll_directory() are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for add_dll_directory() and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer). (Contributed by Steve Dower in bpo-36085.)

**Comment by jorisvandenbossche** [comment]
A potentially related issue about this in Fiona: https://github.com/Toblerity/Fiona/issues/851

**Comment by brendan-ward** [comment]
In case it is helpful here, I had to implement this as a context manager in `pyogrio` (loads GDAL dlls this way): https://github.com/geopandas/pyogrio/blob/master/pyogrio/_env.py

This approach was inspired by what Fiona is doing here: https://github.com/Toblerity/Fiona/blob/maint-1.9/fiona/_loading.py

Though I still have not been able to get things to work properly on Windows CI.  😦

**Comment by caspervdw** [comment]
The issue makes sense to me now. In appveyor, we copy over the dll into the pygeos package dir and all is fine. Also the windows wheel works like that.

I am hestitant to do something like pyogrio does, there must be a good reason for not using the PATH anymore in Python 3.8+. Other options:

- leave it up to the user for putting geos dlls in the pygeos package dir or some system dir (document this for the advanced users that self-build pygeos on windows)
- copy over the dll somewhere in setup.py

**Comment by caspervdw** [comment]
I confirmed in #382 that simply placing the dlls into the pygeos package instead of updating the PATH solves the issue. 

The question remains what we should do for our users that compile pygeos themselves on windows.
