### ISSUE TITLE
Missing Aarch64 wheel for python 3.6, 3.7, 3.8

### ISSUE THREAD

**Issue by odidev** [pygeos/pygeos#384]
In pypi I have seen that wheel for arm64 is released only for python 3.9 and in **.github/workflows/release.yml**  I can see that you are skipping wheel creation for python3.6, 3.7, and 3.8.

It looks that it is because numpy aarcch64 wheels are available for version greater or equal to 1.19. Can we not create python3.6, 3.7, and 3.8 wheels with higher numpy versions(eg. Numpy==1.19 or later)?

**Comment by caspervdw** [comment]
Yes we could in principle do that. There are some practical issues with the pyproject.toml that needs to be overridden on aarch64 builds specifically.

If you have time to look into that it would be greatly appreciated!

**Comment by caspervdw** [comment]
@odidev Aarch64 wheels are now on PyPI for python 3.6-3.10. Thanks for you contribution!
