### ISSUE TITLE
`pygeos.make_valid` incompatible with geometries with `inf` coordinate values

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#388]
A geometry with a `nan` or `inf` coordinate value is considered invalid, however `pygeos.make_valid` doesn't know how to handle them.

```
geometries = np.array([pygeos.creation.linestrings(np.array([[0,1],[1,2],[3,4]]))])
pygeos.make_valid(geometries)

# array([<pygeos.Geometry LINESTRING (0 1, 1 2, 3 4)>], dtype=object)
```

```
geometries = np.array([pygeos.creation.linestrings(np.array([[0,1],[1,np.inf],[3,4]]))])
pygeos.make_valid(geometries)

# GEOSException: IllegalArgumentException: CGAlgorithmsDD::orientationIndex encountered NaN/Inf numbers
```

**Comment by caspervdw** [comment]
Thanks for the report @carlosg-m . As PyGEOS merely wraps the `GEOSMakeValid_r` exposed by the GEOS C API, we can't really do anything about it here.

You may want to create a ticket at GEOS: https://trac.osgeo.org/geos/report
