### ISSUE TITLE
There is no way in Pygeos to filter geometries with `nan` or `inf` coordinate values

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#389]
There should be a way to assert geometries with missing or infinite values.
GeoPandas handles empty geometries `s.is_empty` or geometries with missing values `s.isna()`.

```
a = pygeos.points(np.array([np.nan, np.inf]))
# <pygeos.Geometry POINT (nan inf)>

pygeos.is_geometry(a)
# True

pygeos.is_missing(a)
# False

pygeos.is_valid_input(a)
# True
```

The only workaround I could find is searching for 'Invalid Coordinate' in the string returned by `pygeos.is_valid_reason` but it is not safe:
```
has_invalid_coo = pd.Series(pygeos.is_valid_reason(df['geometry'].values)).str.contains('Invalid Coordinate')
# True
```
Maybe there's something that can be done with `pygeos.get_coordinates`.

**Comment by caspervdw** [comment]
I think that you should be able to do this with `pygeos.get_coordinates` indeed:

```
>>> coords, inds = pygeos.get_coordinates(a, return_index=True)
>>> inds[~np.isfinite(coords).any(1)]
array([0])
```

I don't think we need a separate function to achieve this, because we are thinking of forbidding NaN and inf in geometries anyway.

Please close the issue if this answered your questions.

**Comment by jorisvandenbossche** [comment]
@carlosg-m follow-up question for you: since you opened a few issues with questions related to NaN / Inf coordinates, do you have a specific use case for them? Or is it that they are contained in your data source, and thus you need to handle them in some way? (and what kind of data source does contain NaN/Inf coordinates?)

(it would be interesting for us to have some more context, also for deciding whether we could be more strict about forbidding such values or not when creating geometries. For example, if your have a geospatial data source that allows such values, it might be rather annoying to forbid such values, as in such a case you typically want to "fix" your geometries after reading the file has created them)

**Comment by carlosg-m** [comment]
> @carlosg-m follow-up question for you: since you opened a few issues with questions related to NaN / Inf coordinates, do you have a specific use case for them? Or is it that they are contained in your data source, and thus you need to handle them in some way? (and what kind of data source does contain NaN/Inf coordinates?

My use cases are related with data science and feature engineering for ML models or traditional ad-hoc queries.

I work in the energy sector, and we have custom made legacy GIS software. 

The problem is that datasets that come from this systems are noisy and have all sorts of problems, including Infs, Nans, empty geometries, invalid geometries and so on. I try to preserve as much information as possible, for example a powerline might be misrepresented by a Linestring with a single point, however instead of discarding this invalid record I usually try to fix it and represented it as a single point. 

I was using shapely together with pyspark to parse geojson from these legacy sources, but sometimes some geometries were so corrupted there was nothing that could be done.

However the last time I've encountered the Inf problem was when dealing with projections. The same dataset can contain geometries in WGS84, but also other coordinates in Cartesian planes that represent floor plans. 

A very common preprocessing step we use is intersecting the geometries with the shape of the country they should be in using an official source, to filter out floor plans. When we project coordinates in ETRS89, the Cartesian coordinates from the floor plans, will yield Inf values, that later have to be dealt with.

During the development Pygeos you have to keep in mind that even if the input dataset is relatively clean and valid, some transformations may yield invalid or corrupt outputs. And there should be a way at least to ignore or discarding them without compromising vectorized operations.

There could be an option in some functions to ignore or raise errors given a corrupt input, like in Pandas `{‘ignore’, ‘raise’, ‘coerce’}`. However I have no idea if such behavior is in scope or aligned with your vision of what this lib should do. Since there is no Pygeos method to parse GeoJson you could argue that that all WKT or WKB input geometries that are consumed are assumed to have been serialized properly. But doing so you will force some users to use other libs for preprocessing, and benefit of performance will be lost.
