### ISSUE TITLE
`pygeos.set_precision` creates empty geometries

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#390]
If you round a LineString until you get a single coordinate value, `pygeos.set_precision` returns an empty geometry. Shouldn't it return a single point instead?

```
geometry = pygeos.linestrings([np.array([0.01, 0.02]), np.array([0.03, 0.04]), np.array([0.05, 0.06])])
# <pygeos.Geometry LINESTRING (0.01 0.02, 0.03 0.04, 0.05 0.06)>

pygeos.set_precision(geometry, 1)
# <pygeos.Geometry LINESTRING EMPTY>
```
Expected result:
```
# <pygeos.Geometry POINT (0 0)>
```

**Comment by brendan-ward** [comment]
This is expected behavior and comes directly from GEOS.

See the docstring:
> Line and polygon geometries may collapse to empty geometries if all vertices are closer together than grid_size

**Comment by carlosg-m** [comment]
I borrowed @jorisvandenbossche's code example to project Pygeos geometries and added a "rounding_precision" parameter, simply based on NumPy's round function. 

```
def pygeos_project(geometries, input_crs, output_crs, rounding_precision):
  
  transformer = pyproj.Transformer.from_crs(input_crs, output_crs, always_xy=True)

  coords = pygeos.get_coordinates(geometries)
  coords = transformer.transform(coords[:, 0], coords[:, 1])
  
  geometries = pygeos.set_coordinates(geometries.copy(), np.array(coords).round(rounding_precision).T)
  
  return geometries
```

To avoid using `pygeos.set_precision` and collpasing geometries I implement the following preprocessing pipeline:
1) Serialize geometries from WKT: `pygeos.from_wkt`
2) Filter empty or missing geometries: `pygeos.is_missing`, `pygeos.is_geometry`, `pygeos.is_valid_input`
3) Project and then round geometries' coordinates: `pygeos_project`
4) Filter geometries with Nan or Inf coordinates: `pygeos.is_valid_reason`, `"Invalid Coordinate"`
5) Fix invalid geometries: `pygeos.make_valid`

**Comment by jorisvandenbossche** [comment]
> Using the example above as input this preprocessing pipeline would result in a single Point instead of an empty geometry.

I don't think it will give a single Point, but rather a LineString with two identical points? (get/set_coordinates doesn't change the number of ordinates, neither the type of the geometry)

```python
>>> line = pygeos.Geometry("LINESTRING(0 0, 0.4 0.4)")
>>> res1 = pygeos.set_precision(line, 1)
>>> res1
<pygeos.Geometry LINESTRING EMPTY>
>>> res2 = pygeos.apply(line, lambda x: x.round(0))
res2
<pygeos.Geometry LINESTRING (0 0, 0 0)>
>>> pygeos.is_valid(res2)
False
```

And then you can get invalid geometries as a result. 

In general, "naively" rounding the coordinates has the risk to give identical vertices that don't get collapsed, resulting in invalid geometries. `pygeos.set_precision` includes some logic to keep the result as valid geometries.

**Comment by carlosg-m** [comment]
> In general, "naively" rounding the coordinates has the risk to give identical vertices that don't get collapsed, resulting in invalid geometries. pygeos.set_precision includes some logic to keep the result as valid geometries.

Yes, in my use case I was able to find some examples of invalid linestring with duplicate coordinates, that's why I was using `pygeos.make_valid` function afterwards to fix them. 

However I don't know what kinds of other problems this approach might cause to polygons for example, and if they are fixable. But the idea here was to include as many geometries as possible during analysis.

**Comment by jorisvandenbossche** [comment]
> that's why I was using pygeos.make_valid function afterwards to fix them.

And I see that using `make_valid` on the LineString with 2 equal vertices, indeed gives a Point instead of an empty LineString (as `set_precision` does). 
You could certainly bring it up with the GEOS project if they have a reasoning for collapsing to empty geometries instead of collapsing to a "lower dimension geometry" in `set_precision` (while having a different logic in `make_valid`).
