### ISSUE TITLE
Support excluding input geometry ("itself") in nearest STRtree query

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#400]
Shapely added an `exclusive=True/False` keyword to the STRTree `nearest` method to optionally "exclude the input geometry from the results", see https://github.com/Toblerity/Shapely/pull/1166

The implementation in Shapely currently checks for this based on the "equals" spatial predicate, so it is not necessarily strictly excluding the "input geometry", but any geometry that is spatially equal (so can even have different coordinates). 
(more in general it's of course not possible to exactly exclude the input geometry, unless we would check for exact object _identity_ (same pointer))

**Comment by brendan-ward** [comment]
Duplicate of #324?

**Comment by jorisvandenbossche** [comment]
Whoops, indeed!
