### ISSUE TITLE
Pygeos Pyinstaller issue

### ISSUE THREAD

**Issue by lestegem3** [pygeos/pygeos#407]
I am using pygeos through geopandas. Specifically the sjoin_nearest function. When I run out of pycharm everything works fine. However, I compiled my code using Pyinstaller. It compiles, however when I run the .exe file I receive the following error FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\LSTEGE~1\\AppData\\Local\\Temp\\_MEI122202\\pygeos.libs'

I have pygeos downloaded using pip install. Any solutions for this issue?

**Comment by caspervdw** [comment]
Hi @lestegem3 , good to hear from another PyGEOS user. I am not aware of anyone attempting to package PyGEOS using pyinstaller, and I never attempted to do so myself.

Your error message indicates that the dlls that PyGEOS requires are missing. I glanced over the pyinstaller docs and it seems that only python dependencies are automatically included. So you will have to provide pyinstaller with some extra info to convince it to include the dlls in “pygeos.libs”. I’d raise an issue at pyinstaller if you can’t figure out how to do that.

Please let us know if you get this working or if you have any questions concerning pygeos.

**Comment by caspervdw** [comment]
Hi @MaiaPaulo, sorry you are experiencing issues installing pygeos. However I know next to nothing about pyinstaller so I am afraid I can’t help you here. Maybe you should ask the maintainers of pyinstaller?

**Comment by sharon92** [comment]
@lestegem3 @caspervdw @MaiaPaulo 

You must add the missing dlls and libs in the spec file of PyInstaller.

1. Generate the spec file by calling "pyinstaller yourpygeosscript.py"
2. Find "yourpygeosscript.spec" in the same directory
3. Update the binaries in Analysis object (see below)
4. Compile again with the command "pyinstaller yourpygeosscript.**spec**"

This is what my spec file looks like:
![image](https://user-images.githubusercontent.com/51754340/155178543-59e329f3-bcf2-4957-be86-0a191952bce8.png)

in binaries I added the path to "pygeos.libs" and its contents. In addition I needed to add "pygeos._geos"

After adding the binaries my executable ran without issues.

**Comment by jankovicmmarko18** [comment]
@lestegem3 

Another way that worked for me is: 
1) importing pygeos and pygeos._geos in my project
2) adding to app.spec file:
```
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_dynamic_libs

datas = []
datas += collect_data_files('pygeos')
datas += collect_data_files('pygeos._geos')

a = Analysis(....
datas=datas,
...

```
