### ISSUE TITLE
Revert may_segfault and point empty fix in geojson io

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#423]
Geos 3.10.1 just came out and fixed the crashes in the GeoJSON io functions. 

I think we can revert #418 @brendan-ward

**Comment by brendan-ward** [comment]
Since you are checking against exactly `3.10.0`, it might be OK to leave that fix in place until that version of GEOS has propagated out enough.

Alternatively, you could make 3.10.1 the minimum required version for the geojson functions, and sidestep the segfault altogether...

**Comment by jorisvandenbossche** [comment]
> Alternatively, you could make 3.10.1 the minimum required version for the geojson functions, and sidestep the segfault altogether...

Once GEOS 3.10.1 has landed on conda-forge, +1 on this option
