### ISSUE TITLE
Add wheels for alpine linux

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#428]
These correspond to the "musllinux" builds that are currently skipped in our cibuildwheel config.

**Comment by caspervdw** [comment]
Currently numpy doesn’t provide wheels for this platform; so we would have to start with building numpy. I think that goes to far. We can revisit this once musllinux wheels are supported by numpy.

**Comment by jorisvandenbossche** [comment]
The issue on the numpy side about this: https://github.com/numpy/numpy/issues/20089 (they are also migrating to use cibuildwheel, so I suppose they should now be able to add musllinux)

**Comment by caspervdw** [comment]
I think we will revisit once numpy has a binary distribution for musllinux, closing here.
