### ISSUE TITLE
Side effects between PySpark, Numpy and Pygeos

### ISSUE THREAD

**Issue by carlosg-m** [pygeos/pygeos#440]
I'm using pygeos 0.11.1.

Let's create a simple Pandas Dataframe with a single column named 'id' with a range:
```
df = pd.DataFrame(np.arange(0,1000), columns=['id'])
```
Consider this simple function that selects the first 4 indexes of the 'id' column of an array, and that for some reason calls a Pyegos operation in the beginning. 
```
def udf_example(df):
  
  geo = pygeos.from_wkt(np.array(['POINT (20 30)', 'POINT (34 -2)', 'POINT (20 30)']))
  
  some_index = np.array([0, 1, 2, 3])
  values = df['id'].values[some_index]
  
  df = pd.DataFrame(values, columns=['id'])
  return df
```
If I apply this function in Pyspark I get this result:
```
schema = t.StructType([t.StructField('id', t.LongType(), True)])
df_spark = spark.createDataFrame(df).groupBy().applyInPandas(udf_example, schema)
display(df_spark)

# id
# 125
# 126
# 127
# 128
```
If I apply it in Python I get the correct and expected result:
```
udf_example(df)

# id
# 0
# 1
# 2
# 3
```
Using a Pygeos function together with Spark causes side effects on NumPy indexing operations.

**Comment by jorisvandenbossche** [comment]
And you are sure that applying the function without a pygeos call through pyspark doesn't result in the same issue?

(I don't see any way that pygeos can influence this)

**Comment by carlosg-m** [comment]
You are absolutely right:
```
def udf_example(df):
    
  some_index = np.array([0, 1, 2, 3])
  values = df['id'].values[some_index]
  
  df = pd.DataFrame(values, columns=['id'])
  return df

df = pd.DataFrame(np.arange(0,1000), columns=['id'])

schema = t.StructType([t.StructField('id', t.LongType(), True)])
df_spark = spark.createDataFrame(df).groupBy().applyInPandas(udf_example, schema)
df_spark.show()

# id
# 125
# 126
# 127
# 128
```
The problem seems to be related with Spark. 
I have created a issue on their side: https://issues.apache.org/jira/browse/SPARK-37449
Thanks for the help.
