### ISSUE TITLE
CI: Run the aarch64 build in a different workflow

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#442]
The aarch64 build may take hours while our other builds complete within 10-30 minutes. This is because we use emulation. Also, the build sporadically hangs after which it is killed at 6 hours. There is no way of restarting the build in that case.

I don’t like this as it delays the actual release (which is done only after all envs are completed.

Maybe we can move this build to Travis (which has native support for aarch64) or else move it into an independent workflow so that it does not block the others.

**Comment by jorisvandenbossche** [comment]
This is about the wheel build? 
Both options sound good to me.
