### ISSUE TITLE
GEOS version compatibility with shapely, MacOS and set_operations.intersection/union_all

### ISSUE THREAD

**Issue by nialov** [pygeos/pygeos#447]
# Introduction

When `pygeos` and `shapely` have matching `GEOS` version enabling faster geometry transforms between the packages there is an odd bug in the MacOS platform that does not exist for the Ubuntu platform. I've managed to partly pin this down in this repository:

https://github.com/nialov/pygeos-macos-shapely-incompatibility

The issue is caused by conducting `geopandas.clip` which itself calls `pygeos.set_operations.intersection` (or `pygeos.set_operations.union_all`) which either call `lib.intersection` (or `lib.unary_union`) which return the same error when the `mask` inputted into `geopandas.clip` is a `MultiPolygon` (or when `GEOMETRYCOLLECTION` is passed into `union_all` I'm not certain if in that case the mask was actually a `MultiPolygon`):

~~~
pygeos.GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
~~~

# System

Platform: MacOS (from github actions)

pygeos==0.10.2
geopandas==0.10.2
shapely==1.8.0

~~~
In [17]: from shapely.geos import geos_version_string; geos_version_string
Out[17]: '3.9.1-CAPI-1.14.2'

In [18]: pygeos.geos_capi_version_string
Out[18]: '3.9.1-CAPI-1.14.2'
~~~

# Logs

I've pinned the intersection error here:
https://github.com/nialov/pygeos-macos-shapely-incompatibility/runs/4411204893?check_suite_focus=true

~~~
a = array([<pygeos.Geometry MULTILINESTRING ((4.66e+05 6.69e+06, 4.66e+05 6.69e+06, 4.6...>],
      dtype=object)
b = <pygeos.Geometry MULTIPOLYGON (((4.66e+05 6.69e+06, 4.66e+05 6.69e+06, 4.66e...>
grid_size = None, kwargs = {}

    @multithreading_enabled
    def intersection(a, b, grid_size=None, **kwargs):
        """Returns the geometry that is shared between input geometries.

...

         if grid_size is not None:
            if lib.geos_version < (3, 9, 0):
                raise UnsupportedGEOSOperation("grid_size parameter requires GEOS >= 3.9.0")
    
            if not np.isscalar(grid_size):
                raise ValueError("grid_size parameter only accepts scalar values")
    
            return lib.intersection_prec(a, b, grid_size, **kwargs)
    
>       return lib.intersection(a, b, **kwargs)
E       pygeos.GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
~~~

I also have another repo where the issue was first found when I updated my packages to have matching GEOS as I was interested in the speedup:
https://github.com/nialov/fractopo/runs/4409743659?check_suite_focus=true

Here the same error is raised in `union_all` instead of `intersection` and the issue is I suppose the `GEOMETRYCOLLECTION` of `Polygons` that is passed instead of straight up `MultiPolygon`.

~~~
geometries = array([<pygeos.Geometry POLYGON ((-3 4, 3 4, 3 -3, -3 -3, -3 4))>,
       <pygeos.Geometry POLYGON ((-3 -3.5, 3 -3.5, 3 -5, -3 -5, -3 -3.5))>],
      dtype=object)
grid_size = None, axis = None, kwargs = {}
collections = <pygeos.Geometry GEOMETRYCOLLECTION (POLYGON ((-3 4, 3 4, 3 -3, -3 -3, -3 4)...>

    @multithreading_enabled
    def union_all(geometries, grid_size=None, axis=None, **kwargs):
        """Returns the union of multiple geometries.

...

            if lib.geos_version < (3, 9, 0):
                raise UnsupportedGEOSOperation("grid_size parameter requires GEOS >= 3.9.0")
    
            if not np.isscalar(grid_size):
                raise ValueError("grid_size parameter only accepts scalar values")
    
            result = lib.unary_union_prec(collections, grid_size, **kwargs)
    
        else:
>           result = lib.unary_union(collections, **kwargs)
E           pygeos.GEOSException: IllegalArgumentException: Argument must be Polygonal or LinearRing
~~~

I do not own a MacOS computer myself so I'm somewhat limited in testing for this issue as it is not reproducible on my Ubuntu. Hopefully this report is at least helpful.

**Comment by caspervdw** [comment]
Thanks for raising this issue. To be clear:  does this issue arise if the GEOS versions do not match? If so, this points towards the same shapely-pygeos conversion issues that were discussed in https://github.com/pygeos/pygeos/issues/424 . 

Good news is that pygeos and shapely have merged, so that conversions will not be necessary in the near future.

**Comment by nialov** [comment]
Yes sorry if it was unclear, the issue does not persist if the GEOS versions do not match. So the "solution" to this problem is to make sure they do not match, then the above bug does not occur.

**Comment by jorisvandenbossche** [comment]
I think if you would upgrade pygeos (instead of having it pinned to 0.10), that might also "solve" the issue because of the latest pygeos wheels using a newer GEOS version compared to shapely.

Another solution is to use conda to install shapely and pygeos, which will ensure they actually use the same GEOS library (instead of each having a separate library but with same version)

**Comment by nialov** [comment]
You are correct, I fixed the issue by upgrading `pygeos` to the latest version. But with a `pip` install I lose the compatibility speed gain (not critical of course). I was initially sort of hesitant on reporting this bug as it's not an issue with the latest version but if I understood it correctly it might manifest again when the GEOS version is the same next time when `shapely` catches up again.

**Comment by caspervdw** [comment]
If your want to keep the performance, the only solution *now* is either using conda or compiling shapely and pygeos from source against the same GEOS library.

The shapely 2.0 release will solve these issues, but it may take some time until these changes have boiled up in geopandas. So in the meantime you are stuck using the newest pygeos with shapely 1.x. I don’t expect there will be a shapely 1.x release with GEOS 3.10. (@jorisvandenbossche ?)

**Comment by nialov** [comment]
Thank you for the info! You can do whatever you wish with this issue report

**Comment by caspervdw** [comment]
I’ll close this then. Thanks again for the report!

**Comment by jorisvandenbossche** [comment]
> I don’t expect there will be a shapely 1.x release with GEOS 3.10.

There is probably a good chance we do a 1.8.1 at some point (and then it might make sense to have it include GEOS 3.10), but there are not yet concrete plans.
