### ISSUE TITLE
pygeos lib folder

### ISSUE THREAD

**Issue by mvnayagam** [pygeos/pygeos#449]
HI everyone,

I am very new to the field of Python. for my project I am trying to use pygeos. before this, I want to go through the files in this package.
 
in the pygeos/pygeos/__init_.py file, at lines number 1 to 4, I see the following

from .lib import GEOSException  # NOQA
from .lib import Geometry  # NOQA
from .lib import geos_version, geos_version_string  # NOQA
from .lib import geos_capi_version, geos_capi_version_string  # NOQA

But I do not see any .lib directory in pygeos/pygeos/ dir.

can anyone explain where can I see .lib folder/file.??

I appreciate your effort to explain this concept !!!

thank you

**Comment by brendan-ward** [comment]
`.lib` refers to a [compiled C extension](https://github.com/pygeos/pygeos/blob/master/setup.py#L159) rather than a folder; the extension gets compiled into a file in the `pygeos` folder that is named based on your architecture and Python version, e.g., `lib.cpython-39-darwin.so`.
