### ISSUE TITLE
Support to pickle Geometry objects

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#46]
I think this will involve defining `__reduce__` or `__setstate__` / `__getstate__` or some of the related methods that are involved in pickling.

With @pierreglaser, we did some work on this at EuroScipy (while actually trying to do the dtype), and there is some content to reuse in https://github.com/pierreglaser/pygeos/commit/0e0ea8e0e0ce28b34502cba37382121b1ee064b9

**Comment by jorisvandenbossche** [comment]
This will also solve that you can "copy" a scalar geometry object (or deepcopy an array), which falls back to pickling:

```
In [18]: p = pygeos.points(1, 1) 

In [19]: import copy 

In [20]: copy.copy(p)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-288b2fe1bef4> in <module>
----> 1 copy.copy(p)

~/miniconda3/envs/geo-dev/lib/python3.7/copy.py in copy(x)
     94         reductor = getattr(x, "__reduce_ex__", None)
     95         if reductor:
---> 96             rv = reductor(4)
     97         else:
     98             reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle pygeos.ufuncs.GEOSGeometry objects
```

(we could actually also implement a custom `__copy__` using geos methods, though, but implementing pickle seems useful anyway)

**Comment by caspervdw** [comment]
I think that the `__copy__` should just return `self`.

A central design of pygeos is that geometry objects are immutable. Hence copying them doesn't make any sense: they can't be changed. Other immutable types like `int` are also not copyable Example:

```
>>> from copy import copy
>>> a = 1
>>> b = copy(a)
>>> a is b
True
```

**Comment by jorisvandenbossche** [comment]
> I think that the __copy__ should just return self.

Yes, fully agree on the immutability. I was just pointing out our finding that copying actually involved pickling (we were a bit surprised at first), but implementing actually a `__copy__` and adding that to the Geometry object shouldn't be hard.
