### ISSUE TITLE
incompatible GEOS version with shapely

### ISSUE THREAD

**Issue by bardout** [pygeos/pygeos#462]
#### env
using latest pygeos and shapely, from anaconda on linux:
```
$ python --version
Python 3.11.3
$ conda list|egrep "shapely|pygeos"
pygeos                    0.14                     pypi_0    pypi
shapely                   2.0.1           py311h54d622a_1    conda-forge

```
Latest pygeos  0.14 from Dec 12, 2022, but shapely  change log:
- 2.0.1 (2023-01-30)  .       
- 2.0b1 (2022-10-17): Wheels for 2.0b1 published on PyPI include GEOS 3.11.0.       
- 2.0a1 (2022-08-03): Wheels for 2.0a1 published on PyPI include GEOS 3.10.3.

#### observation
run raise:  geopandas/_compat.py:123: _UserWarning: The Shapely GEOS version (3.11.2-CAPI-1.17.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow._

my code does use geopandas with 'USE_PYGEOS=1, and also need some direct shapely operations, not provided by geopandas

### expected: 
a release compiled with the _GEOS version 3.11.2_ to benefit from stable shapely release

**Comment by samfux84** [comment]
Same issue here:

/cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pygeos/io.py:89: UserWarning: The shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the PyGEOS GEOS version (3.9.1-CAPI-1.14.2). Conversions between both will be slow.

Not sure how to resolve this version conflict ...

```
[sfux@eu-login-30 ~]$ pip list | egrep "Shapely|pygeos"
pygeos                          0.14
Shapely                         1.8.5

[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
[sfux@eu-login-30 ~]$
```

GEOS 3.9.1 built from source. For building Shapely and pygeos I used:

pip install --no-binaries :all: Shapely pygeos

Both packages are linked to exactly the same GEOS 3.9.1 library:

[sfux@eu-login-30 ~]$ ldd /cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/shapely/speedups/_speedups.cpython-310-x86_64-linux-gnu.so | grep libgeos.so
        libgeos.so.3.9.1 => /cluster/spack/apps/linux-centos7-x86_64/gcc-8.2.0/geos-3.9.1-zrnzxk4eykfbs6oms3yhskxigbdkqgyp/lib/libgeos.so.3.9.1 (0x00002b41add7d000)
[sfux@eu-login-30 ~]$ ldd /cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/shapely/vectorized/_vectorized.cpython-310-x86_64-linux-gnu.so | grep libgeos.so
        libgeos.so.3.9.1 => /cluster/spack/apps/linux-centos7-x86_64/gcc-8.2.0/geos-3.9.1-zrnzxk4eykfbs6oms3yhskxigbdkqgyp/lib/libgeos.so.3.9.1 (0x00002abe93b94000)
[sfux@eu-login-30 ~]$ ldd /cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pygeos/_geometry.cpython-310-x86_64-linux-gnu.so | grep libgeos.so
        libgeos.so.3.9.1 => /cluster/spack/apps/linux-centos7-x86_64/gcc-8.2.0/geos-3.9.1-zrnzxk4eykfbs6oms3yhskxigbdkqgyp/lib/libgeos.so.3.9.1 (0x00002ad4a6811000)
[sfux@eu-login-30 ~]$ ldd /cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pygeos/_geos.cpython-310-x86_64-linux-gnu.so | grep libgeos.so
        libgeos.so.3.9.1 => /cluster/spack/apps/linux-centos7-x86_64/gcc-8.2.0/geos-3.9.1-zrnzxk4eykfbs6oms3yhskxigbdkqgyp/lib/libgeos.so.3.9.1 (0x00002b1001b53000)
[sfux@eu-login-30 ~]$ ldd /cluster/apps/nss/gcc-8.2.0/python/3.10.4/x86_64/lib64/python3.10/site-packages/pygeos/lib.cpython-310-x86_64-linux-gnu.so | grep libgeos.so
        libgeos.so.3.9.1 => /cluster/spack/apps/linux-centos7-x86_64/gcc-8.2.0/geos-3.9.1-zrnzxk4eykfbs6oms3yhskxigbdkqgyp/lib/libgeos.so.3.9.1 (0x00002b8d8b182000)
[sfux@eu-login-30 ~]$

**Comment by martinfleis** [comment]
Ideally, you should no longer use pygeos alongside shapely and switch to shapely. There's no need for pygeos anymore. If you see these warnings because of GeoPandas, please update GeoPandas to 0.14 which defaults to shapely. I suppose that there will be no interest from maintainers of PyGEOS/Shapely to figure this out given PyGEOS was merged to shapely and is no longer developed as an independent project.

**Comment by bardout** [comment]
I finished this project, but thanks, that is good news to simplify the installation with efficient topology library.

**Comment by bardout** [comment]
So I guess, issue is solved for me. Samfux84 can check it.

**Comment by samfux84** [comment]
@bardout: I could resolve the issue by upgrading Shapely from version 1.8.5 to 2.0.2. Geopandas checks the Shapely version and if it is smaller than 2.0.0, then PyGEOS is used as backend. By updating Shapely to 2.0.2, geopandas will use Shapely as backend and the error is gone as PyGEOS is not called any more.

So everything fine on my side. Issue is resolved.
