### ISSUE TITLE
ENH: add support for Polygonize

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#55]
Wrap GEOSPolygonize, similarly to shapely (https://shapely.readthedocs.io/en/latest/manual.html#shapely.ops.polygonize)

**Comment by HTenkanen** [comment]
@jorisvandenbossche Any updates on this one? Would have a need for this. :slightly_smiling_face: I can also try to help out with this one if needed.

**Comment by jorisvandenbossche** [comment]
You are certainly always welcome to try to contribute it! (I might otherwise get to it in a few weeks)

**Comment by jorisvandenbossche** [comment]
This has been fixed by https://github.com/pygeos/pygeos/pull/275, will be available in the next pygeos release
