### ISSUE TITLE
Fix the ToWKB for empty points

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#60]
The WKB spec does not allow empty points. Some reads:

https://github.com/Toblerity/Shapely/issues/742
https://trac.osgeo.org/postgis/ticket/3181

If I'm correct (needs checking), we should serialize it to POINT (NaN, NaN), and deserialize back to POINT EMPTY.

**Comment by caspervdw** [comment]
Duplicates #134

**Comment by caspervdw** [comment]
Upon further consideration, I think this is something to be solved upstream in GEOS. There is already a ticket for it: https://trac.osgeo.org/geos/ticket/1005

**Comment by brendan-ward** [comment]
@caspervdw since this does not have an immediate fix in `pygeos` it would be best to leave this out of the 0.8 milestone.

Other than tracking GEOS for updates - which looks perhaps a bit unlikely given the history of the related issues there - what changes are necessary in `pygeos`?  Should we instead develop a `pygeos` specific work-around?

**Comment by mwtoews** [comment]
If this is a simple workaround with pygoes, I would advise this option, as GEOS issues tend to take a while to get noticed and fixed. (I have made some attempts to patch this, but my lack of C++ know-how is holding me back in completing this).

**Comment by jorisvandenbossche** [comment]
There seems to be some movement in GEOS! (https://trac.osgeo.org/geos/ticket/1005, at least it is commented that JTS applied this fix, so I think GEOS can/will follow suite if someone contributes the fix). 

Now, given that we support multiple versions of GEOS, I think it would still be useful to also add the special case here, to ensure consistent behaviour across GEOS versions.

**Comment by mwtoews** [comment]
This is now fixed in https://github.com/libgeos/geos/commit/466cff135c8e504632ae38b79a1348dbadb390f1 for version 3.9.0 (thanks @pramsey !)
