### ISSUE TITLE
ENH: bounds function

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#62]
Shapely has a `bounds` attribute, implemented at:

https://github.com/Toblerity/Shapely/blob/803b21bb87f3f76ce25bec4e015b46038c0df1f4/shapely/coords.py#L159-L186

I personally find this a useful operation that I use regularly. You can already get the coordinates per geometry and calculate the min/max of this, but doing that on an array of geometries still requires some manual looping.

Something to add to pygeos?

**Comment by jorisvandenbossche** [comment]
Postgis seems to have something related: `ST_Extent` (https://postgis.net/docs/ST_Extent.html). But this returns a "BOX" object instead of the 4 values as `bounds` does. And it is also an aggregation function (so it typically creates the bounding box of multiple geometries, I suppose, similarly to the `total_bounds` in GeoPandas)

The "spatial" equivalent is actually the `pygeos.envelope` function, which gives you the polygon representation of this bounding box. But from there it is still not that straightforward to get the 4 bounding coordinates.

**Comment by caspervdw** [comment]
The GEOS C-API exposes Xmin, Xmax, Ymin, Ymax functions since version 3.7. That is probably what we need. I do wonder if performing the `envelope` and getting the values from the coordinate sequence would be more efficient.

**Comment by caspervdw** [comment]
As discussed in #69, we would also like a total_bounds function

**Comment by brendan-ward** [comment]
@caspervdw this appears resolved as of #69, #107

**Comment by jorisvandenbossche** [comment]
Indeed!
