### ISSUE TITLE
Add __geo_interface__ protocol

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#65]
See https://gist.github.com/sgillies/2217756

That would ensure that pygeos.Geometry objects would be recognized in places that use this protocol.

**Comment by brendan-ward** [comment]
Requires polygon rings to be in proper clockwise / counterclockwise direction, per #71 .

**Comment by brendan-ward** [comment]
Because `Geometry` (`GeometryObject`) is defined in C, I'm not seeing a way to extend that class on the Python side (as suggested [here](https://github.com/pygeos/pygeos/issues/82#issuecomment-580387396)).

I also haven't seen cases of using Cython to extend the class to add methods like this, but still use the underlying class from C in ufuncs.

My sense is that this - and any other methods / properties we want to define on the class - needs to be defined in C.

**Comment by jorisvandenbossche** [comment]
>  I'm not seeing a way to extend that class on the Python side

There is some experimentation on that in https://github.com/pygeos/pygeos/pull/104

**Comment by brendan-ward** [comment]
That seems like that would help this case as well, it would allow us to add a specific `__geo_interface__` to each subclass instead of the base class.  

This makes sense to tackle after those changes are in place.

**Comment by caspervdw** [comment]
As GEOS 3.10 now supports GeoJSON, it should be relatively easy to implement this on the C level; just serialize to string and reconstitute to Python objects with “json.loads”. In the Geometry constructor we could do the reverse.

Only issue I see is the LinearRing, which has no place in GeoJSON.

**Comment by brendan-ward** [comment]
Even though not supported by the GeoJSON spec, Shapely seems to happily output them:

```
>>> from shapely.geometry import LinearRing
>>> ring = LinearRing([[0,0], [0,1], [1,1], [1,0], [0,0]])
>>> ring.__geo_interface__
{'type': 'LinearRing', 'coordinates': ((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0))}
```

**Comment by jorisvandenbossche** [comment]
Now we are merging, this is already implemented in Shapely for the scalar subclasses. For example for LineString: https://github.com/Toblerity/Shapely/blob/a0f8a31a18d5384f0a04ee8e8b2d089b37c186cc/shapely/geometry/linestring.py#L72-L77, or for Polygon: https://github.com/Toblerity/Shapely/blob/a0f8a31a18d5384f0a04ee8e8b2d089b37c186cc/shapely/geometry/polygon.py#L271-L281

It's a relatively straightforward implementation, so I don't know if there would be much benefit in refactoring that as parsing the GeoJSON output.

**Comment by caspervdw** [comment]
Agreed, closing
