### ISSUE TITLE
Release the GIL where possible

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#7]
To take advantage of multithreading possibilities, we should release the GIL whenever we do operations that do not involve PyObjects (most of them)

**Comment by jorisvandenbossche** [comment]
Currently, the ufunc inner loop functions still have python interaction. Eg the ones that return a geometry:

https://github.com/caspervdw/pygeos/blob/e885283d23b26775512cd4b8810786bcc4ac15f4/src/ufuncs.c#L43-L55

But also in the input handling

https://github.com/caspervdw/pygeos/blob/e885283d23b26775512cd4b8810786bcc4ac15f4/src/ufuncs.c#L32-L34

the `get_geom` function deals with Python objects.

So that seems a problem for releasing the GIL here with the current approach?

**Comment by jorisvandenbossche** [comment]
In the `get_geom` function

https://github.com/caspervdw/pygeos/blob/e885283d23b26775512cd4b8810786bcc4ac15f4/src/ufuncs.c#L397-L418

it seems this is mainly for the cases where the input is not a GeometryObject struct but None or np.nan ? 
So here, a solution might be to have a missing value indicator that is also a GeometryObject ? (eg with a null pointer)

**Comment by caspervdw** [comment]
The functions that create new geometries definitely cannot release the GIL. I could collect the C pointers in an initial loop and then replace them with Python objects in a second, which would leave most of the time to release the GIL.

Concerning the inputs, I have to read up on this, but my it is my impression that only reading from a static attribute from an object will be possible without the GIL. Do you know if this is possible? Otherwise the same approach as above could be taken: first collect the pointers, then execute the GEOS functions without GIL

**Comment by jorisvandenbossche** [comment]
I sent an email to the numpy mailing list to ask about this, whether it is possible to let numpy release the GIL in the case where we only need access to the pointer attribute (I think by default it does not release the GIL in ufuncs if the arrays are of object dtype).

For collecting the pointers first: that would mean that all ufuncs are written for arrays of only pointers, and then the level above that (the python wrappers?) ensures to first create this array of pointers and calls the ufunc on those? (and potentially wrap again in the end)

I was doing a quick profiling of both steps separately with the contains in cython. And for this case, collecting the pointers takes around 10% of the time of the actual contains operation. So that might be acceptable

**Comment by caspervdw** [comment]
> I sent an email to the numpy mailing list to ask about this,

Thanks!!

I think that the two forloop approach should be done completely in C. I don't want C pointers to go to the python level, this opens up possibilities of segfaults. 

For example here: https://github.com/caspervdw/pygeos/blob/e885283d23b26775512cd4b8810786bcc4ac15f4/src/ufuncs.c#L551 , instead of the `OUTPUT_Y` macro, we should just put the GEOSGeometry pointer inside the output array `out` (without GIL). Then on a second loop (right after the `UNARY_LOOP` in the linked code), these can be wrapped by the python objects (with GIL).

> I was doing a quick profiling of both steps separately with the contains in cython. And for this case, collecting the pointers takes around 10% of the time of the actual contains operation. So that might be acceptable

That is certainly promising. Did you use the rectangle-contains-point benchmark?  I see that as a 'worst case' as by far most GEOS operations would be more heavy.

**Comment by jorisvandenbossche** [comment]
> Did you use the rectangle-contains-point benchmark? I see that as a 'worst case' as by far most GEOS operations would be more heavy.

Yes, the contains operation is indeed one of the relatively fast operations.

> I think that the two forloop approach should be done completely in C

OK, I tried something similar to your suggestion.

The current function (with expanded macro's) for contains (YY_b) looks like:

```c
static void YY_b_func(char **args, npy_intp *dimensions,
                      npy_intp *steps, void *data)
{
    FuncGEOS_YY_b *func = (FuncGEOS_YY_b *)data;
    void *context_handle = geos_context[0];
    GEOSGeometry *in1, *in2;

    // BINARY_LOOP
    char *ip1 = args[0], *ip2 = args[1], *op1 = args[2];
    npy_intp is1 = steps[0], is2 = steps[1], os1 = steps[2];
    npy_intp n = dimensions[0];
    npy_intp i;
    for(i = 0; i < n; i++, ip1 += is1, ip2 += is2, op1 += os1) {
        //INPUT_YY;
        if (!get_geom(*(GeometryObject **)ip1, &in1)) { return; }
        if (!get_geom(*(GeometryObject **)ip2, &in2)) { return; }

        npy_bool ret = func(context_handle, in1, in2);

        //OUTPUT_b;
        if (! ((ret == 0) || (ret == 1))) {
            RAISE_ILLEGAL_GEOS;
            return;
        }
        *(npy_bool *)op1 = ret;
    }
}
```

If I change this to

```c
static void YY_b_func(char **args, npy_intp *dimensions,
                      npy_intp *steps, void *data)
{
    FuncGEOS_YY_b *func = (FuncGEOS_YY_b *)data;
    void *context_handle = geos_context[0];
    GEOSGeometry *in1, *in2;

    // BINARY_LOOP
    char *ip1 = args[0], *ip2 = args[1], *op1 = args[2];
    npy_intp is1 = steps[0], is2 = steps[1], os1 = steps[2];
    npy_intp n = dimensions[0];
    npy_intp i;

    GEOSGeometry **geoms1 = malloc(sizeof(void *) * dimensions[0]);
    GEOSGeometry **geoms2 = malloc(sizeof(void *) * dimensions[0]);

    for(i = 0; i < n; i++, ip1 += is1, ip2 += is2) {
        if (!get_geom(*(GeometryObject **)ip1, &in1)) { return; }
        if (!get_geom(*(GeometryObject **)ip2, &in2)) { return; }
        geoms1[i] = in1;
        geoms2[i] = in2;
    }

    NPY_BEGIN_THREADS_DEF;
    NPY_BEGIN_THREADS;
    for(i = 0; i < n; i++, op1 += os1) {
        //INPUT_YY;
        in1 = geoms1[i];
        in2 = geoms2[i];

        npy_bool ret = func(context_handle, in1, in2);

        //OUTPUT_b;
        if (! ((ret == 0) || (ret == 1))) {
            RAISE_ILLEGAL_GEOS;
            return;
        }
        *(npy_bool *)op1 = ret;
    }
    NPY_END_THREADS;
    if (geoms1 != NULL) { free(geoms1); }
    if (geoms2 != NULL) { free(geoms2); }
}
```

where in a first loop over the inputs I create `GEOSGeometry **` arrays, and then in the second loop over the output I do the actual GEOS operation in a part that releases the GIL. 
This still seems to work correctly (I only suppose that the `RAISE_ILLEGAL_GEOS` is not safe to do inside the nogil part, that needs some further handling). And it gives (for the polygon-contains-points example) a 2x à 3x speed-up when done in parallel.

Does the above code looks more or less OK? (I would need to convert it again into macro's then)
