### ISSUE TITLE
Function to check or correct the "orient" of polygons

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#71]
Shapely has a `orient` function to make a copy of a Polygon with "proper" orientation of the rings: https://shapely.readthedocs.io/en/latest/manual.html#shapely.geometry.polygon.orient  (definition in the code: https://github.com/Toblerity/Shapely/blob/b21a964a56a86cf77c67b477db7e7c2e81d2ccb5/shapely/geometry/polygon.py#L391-L404)

In addition, Shapely also has a `is_ccw` (is counter clock wise) attribute on LinearRings: https://shapely.readthedocs.io/en/latest/manual.html#object.is_ccw 

For this, there is a GEOS C API function: https://github.com/libgeos/geos/blob/eb4da1440836fedf503e1eb2c245595a0f33db5e/capi/geos_c.h.in#L351-L357 (although Shapely implements it manually by calculating the signed area)

**Comment by jorisvandenbossche** [comment]
Postgis also has a set of methods related to this: `ST_ForcePolygonCCW`, `ST_ForcePolygonCW` , `ST_IsPolygonCCW` , `ST_IsPolygonCW` (see eg https://postgis.net/docs/ST_ForcePolygonCCW.html)

**Comment by jorisvandenbossche** [comment]
Possible related to this is also GEOSNormalize_r (https://postgis.net/docs/ST_Normalize.html)

**Comment by caspervdw** [comment]
#126 --> implement `is_ccw`

**Comment by jorisvandenbossche** [comment]
It's potentially a bit more than just `is_ccw`, eg both Shapely and Postgis also have functions to convert to consistent orientation, in addition to checking the orientation.

**Comment by caspervdw** [comment]
Ok sorry I was a bit fast closing this then. Let’s investigate!

**Comment by jorisvandenbossche** [comment]
I opened an equivalent function in Shapely: https://github.com/shapely/shapely/issues/1366, so let's close here.
