### ISSUE TITLE
include shared_paths function

### ISSUE THREAD

**Issue by mattijn** [pygeos/pygeos#73]
Firstly, congrats on this package! It looks much promising!

I noticed that the `pygeos.shared_paths()` function was written out of the package in https://github.com/pygeos/pygeos/pull/53. It would be great to have it back!

I tried to include the removed code again and got it somehow working (see code [change](https://github.com/pygeos/pygeos/compare/master...mattijn:MH/add-shared-paths)), see below for some tests. Not sure how to continue or which output/dimension is looked after to make the function reappear. 

The tests I did:

```python
from shapely import geometry
import pygeos
import numpy as np
from IPython.display import SVG, display
```

```python
def svg_style(lines):
    svg_lines = lines._repr_svg_()
    svg_lines = svg_lines.replace('stroke="#66cc99"', 'stroke="orange"', 1)
    svg_lines = svg_lines.replace('stroke-width="0.0432"', 'stroke-width="0.1"', 1)
    svg_lines = svg_lines.replace('opacity="0.8"', 'opacity="0.4"', 1)

    display(SVG(svg_lines))    
```

```python
# prepare some linestrings
g1 = geometry.LineString([(0, 0), (1, 0), (1, 1), (0, 1), (0, 0)])
g2 = geometry.LineString([(1, 0), (2, 0), (2, 1), (1, 1), (1, 0)])
g3 = geometry.LineString([(0, 0), (2, 0), (2, 1), (0, 1), (0, 0)])
```

```python
# shared paths in opposite direction of both inputs
lines_opposite_direction = geometry.MultiLineString([g1, g2])

# orange is g1
# green is g2
svg_style(lines_opposite_direction)
```

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5186265/68161460-37cd9100-ff56-11e9-8e5a-b3e6c829274c.png">

```python
# shared paths in same direction of both inputs
lines_same_direction = geometry.MultiLineString([g1,g3])

# orange is g1
# green is g3
svg_style(lines_same_direction)
```

<img width="500" alt="image" src="https://user-images.githubusercontent.com/5186265/68161511-50d64200-ff56-11e9-8d26-6bc7e072d364.png">

```python
# convert to pygeos
pyg1 = pygeos.from_wkt(g1.wkt)
pyg2 = pygeos.from_wkt(g2.wkt)
pyg3 = pygeos.from_wkt(g3.wkt)
```

```python
# only contain shared paths in backward direction
pygeos.shared_paths(pyg1, pyg2)
```

    <pygeos.Geometry GEOMETRYCOLLECTION (MULTILINESTRING EMPTY, MULTILINESTRING ((1 0, 1 1)))>

```python
# only contain shared paths in forward direction
pygeos.shared_paths(pyg1, pyg3)
```

    <pygeos.Geometry GEOMETRYCOLLECTION (MULTILINESTRING ((0 0, 1 0), (1 1, 0 1), (0 1, 0 0)), MULTILINESTRING EMPTY)>

```python
# prepare as Numpy array
arr_g1g1 = np.array([pyg1, pyg1])
arr_g2g3 = np.array([pyg2, pyg3])
```

```python
# compute shared_paths using arrays
arr_shared_paths = pygeos.shared_paths(arr_g1g1, arr_g2g3)
arr_shared_paths
```

    array([<pygeos.Geometry GEOMETRYCOLLECTION (MULTILINESTRING EMPTY, MULTILINESTRING ((1 0, 1 1)))>,
           <pygeos.Geometry GEOMETRYCOLLECTION (MULTILINESTRING ((0 0, 1 0), (1 1, 0 1), (0 1, 0 0)), MULTILINESTRING EMPTY)>],
          dtype=object)

```python
arr_shared_paths[0]
```

    <pygeos.Geometry GEOMETRYCOLLECTION (MULTILINESTRING EMPTY, MULTILINESTRING ((1 0, 1 1)))>

```python
# try to get the 2nd item from the geometry collection [MULTILINESTRING ((1 0, 1 1))]
arr_shared_paths[0][1]
```

    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    <ipython-input-12-e427a0a9c0f9> in <module>
          1 # try to get the 2nd item from the geometry collection [MULTILINESTRING ((1 0, 1 1))]
    ----> 2 arr_shared_paths[0][1]
    

    TypeError: 'pygeos.lib.GEOSGeometry' object is not subscriptable

```python
# try to get number of geometries (should be 2)
pygeos.get_num_geometries(arr_shared_paths[0])
```

    2

```python
# try to get the 2nd item from the geometry collection
bw_shared_ls = pygeos.get_geometry(arr_shared_paths[0], 1)
bw_shared_ls
```

    <pygeos.Geometry MULTILINESTRING ((1 0, 1 1))>

```python
pygeos.get_coordinates(bw_shared_ls)
```

    array([[1., 0.],
           [1., 1.]])

```python
# try to get the 1st (empty) item from the geometry collection
fw_shared_ls = pygeos.get_geometry(arr_shared_paths[0], 0)
fw_shared_ls
```

    <pygeos.Geometry MULTILINESTRING EMPTY>

```python
pygeos.get_coordinates(fw_shared_ls)
```

    array([], shape=(0, 2), dtype=float64)

```python
# compare with shapely:
from shapely.ops import shared_paths
combs = [[g1, g2], [g1, g3]]
```

```python
%%timeit
list_shared_paths = []
for comb in combs:
    list_shared_paths.append(shared_paths(comb[0], comb[1]))
```

    208 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

```python
%%timeit
arr_shared_paths = pygeos.shared_paths(arr_g1g1, arr_g2g3)
```

    185 µs ± 863 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)

**Comment by mattijn** [comment]
I did some further testing, but only notice a tiny speedup with real-world data. 

I use the `naturalearth_lowres` dataset from geopandas (the `nybb` dataset seems too big already). Firstly all geometries are exploded to single LineStrings which are then compared with all other LineStrings to find shared paths¹. I do this using both the shapely approach and pygeos approach:

```python
import geopandas as gpd
import numpy as np
import itertools
import pygeos
from shapely.ops import shared_paths
from shapely.geometry import MultiLineString

def mls2ls(x):
    if isinstance(x, MultiLineString):
        return [ls for ls in x]
    else:
        return [x]

# load geometries in geodataframe    
data = gpd.datasets.get_path("naturalearth_lowres")
# data = gpd.datasets.get_path("nybb")
gdf = gpd.read_file(data)

# convert geometries to list of linestrings 
mls = gdf.geometry.boundary
# mls = gdf[gdf.continent == 'Europe'].geometry.boundary

# in shapely format 
shapely_ls = sum(mls.apply(mls2ls), [])
shapely_pairs = list(itertools.product(*[shapely_ls, shapely_ls]))

# and pygeos format
pygeos_ls = np.array([pygeos.from_wkt(ls.wkt) for ls in shapely_ls])
pygeos_pairs = np.array(list(itertools.product(*[pygeos_ls, pygeos_ls])))
```

```python
%%timeit
pygeos_shared_paths = pygeos.shared_paths(pygeos_pairs[:,0], pygeos_pairs[:,1])
```

    2.38 s ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)



```python
%%timeit
shapely_shared_paths = [shared_paths(pair[0], pair[1]) for pair in shapely_pairs]
```

    2.84 s ± 5.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Or I do something wrong in using pygeos (hopefully) or this `shared_paths` function cannot be broadcasted on the GEOS side?

¹ (in [topojson](https://github.com/mattijn/topojson) I use the shapely STRtree for preprocessing to only compare LineStrings where the envelope overlap each other, but in this test its excluded).

**Comment by jorisvandenbossche** [comment]
@mattijn first, thanks for your interest in the project! (and sorry for the slow reply)

> I noticed that the pygeos.shared_paths() function was written out of the package in #53. It would be great to have it back!

Not fully sure if that was done on purpose for some reason or an accidental oversight (@caspervdw ?) 
But given that it is a function in the GEOS API (and eg also exposed in Postgis), I think we want to include it eventually in pygeos as well.

> I tried to include the removed code again and got it somehow working (see code change),

If you want to open a PR based on this branch, that's certainly welcome (that makes it easier to comment on the actual code)

> I did some further testing, but only notice a tiny speedup with real-world data.

From a quick look, I don't think you did something wrong in the test case. 
My guess is that this function is a relatively expensive function. That means that most of the time spent is inside the actual shared path GEOS algorithm (and both pygeos and shapely are using the same GEOS algorithm under the hood). In the end, pygeos can only optimize the code around GEOS (ensuring to call it from a C loop instead from a Python loop, to reduce Python overhead).  
Therefore, in this case, pygeos only gives a small speed-up. It still gives the automatic broadcasting / array-based API so you don't need to write the list comprehension.

> in topojson I use the shapely STRtree for preprocessing to only compare LineStrings where the envelope overlap each other, but in this test its excluded

Given that the actual shared path algorithm is expensive, using a spatial index can probably very beneficial indeed. We are working on a STRTree in pygeos as well: https://github.com/pygeos/pygeos/pull/58.
