### ISSUE TITLE
Citation for Pygeos

### ISSUE THREAD

**Issue by seberg** [pygeos/pygeos#85]
We are looking into a new numpy paper, and I thought of listing pygeos as one of the current custom dtypes, which would probably get along better with NumPy if we had new dtypes. Would the EuroScipy talk be good to cite?

**Comment by caspervdw** [comment]
Hi @seberg, good to hear that our work is picked up. I am not aware of a EuroScipy talk (maybe @jorisvandembossche ?)

I think currently the best reference would be my blogpost at https://caspervdw.github.io/Introducing-Pygeos/

**Comment by jorisvandenbossche** [comment]
Yes, I didn't do a talk at EuroScipy (only at FOSS4G Belgium, https://jorisvandenbossche.github.io/talks/2019_FOSS4GBE_pygeos/#1, but @caspervdw's blog is a better reference).

If you want an actual citation reference, we could make a Zenodo doi ?

**Comment by caspervdw** [comment]
I can basically flip a switch on Zenodo to make the citation (did it recently for trackpy). Would be nice to have! Shall I do it @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
That sounds good!

**Comment by seberg** [comment]
I have to admit, I think the mention was dropped from our numpy paper draft with the section that mentioned it being shortened, but I suppose it is good to have in any case :).

**Comment by caspervdw** [comment]
I flipped the switch at Zenodo, a DOI should be automatically created on the next release.

**Comment by caspervdw** [comment]
Done: see Readme for the new badge
