### ISSUE TITLE
Add pytest-benchmark for creating basic benchmarks

### ISSUE THREAD

**Issue by brendan-ward** [pygeos/pygeos#90]
I've had good luck using [`pytest-benchmark`](https://github.com/ionelmc/pytest-benchmark) in other projects.  It is lightweight and easy to setup as part of the overall testing suite, and is easy to reuse other test fixtures.

While it doesn't necessarily ensure deterministic timings esp. on CI platforms, it could provide a good relative measure for comparing between different approaches to a given solution.

The purpose of this issue is simply to determine if you are open to including it for benchmarks.  If so, I could take a quick pass at adding a few simple examples.

**Comment by brendan-ward** [comment]
`asv` probably works OK where it integrates nicely with your existing dependency management / virtual environment approach for a given library, and for a developer's local setup.

Since I don't use `conda` for local development, I was unable to get up and running with the benchmark suite for `geopandas` - which was a barrier to adding benchmarks around new features like `parquet` support.

I appreciate the degree of control `asv` gives you over your benchmark suite, but it also brings with it potential complexity in your environment setup.  

In contrast, I've had no issues getting up and running quickly with `pytest-benchmark`, and the approach feels familiar compared to creating `pytest` tests in general.  Less new things to learn and less work around environment setup.

**Comment by jorisvandenbossche** [comment]
> I was unable to get up and running with the benchmark suite for geopandas - which was a barrier to adding benchmarks around new features like parquet support.

Can you explain a bit what didn't work? As in that case, we should make it easier to get this up and running. I suppose it is always trying to use conda, because that is specified in geopandas' asv.conf. Does it work if you change that to `"virtualenv"` ? 
(we might also be able to remove it, so it tries to infer which of the two to use based on your environment, according to the comments in the conf file)

**Comment by caspervdw** [comment]
I recovered some old work using airspeed velocity. See https://github.com/pygeos/pygeos/pull/96 and https://pygeos.github.io/pygeos

**Comment by brendan-ward** [comment]
This prompted me to try `asv` again.  `virtualenv` didn't work for me (I use `pyenv` + `pipenv` normally).  

However, after getting `conda` setup locally, I was able to run #96.  (thanks @caspervdw !).  That seems like a reasonable path forward for benchmarks.

**Comment by brendan-ward** [comment]
Superseded by #96
