### ISSUE TITLE
BUG: get/set_coordinates modifies the original geometries

### ISSUE THREAD

**Issue by jorisvandenbossche** [pygeos/pygeos#94]
The `set_coordinates` docstring indicates that it "Returns a copy of a geometry array with different coordinates."

However, this doesn't seem to be working correctly:

```In [31]: arr = pygeos.points([1, 2, 3], [1, 2, 3])

In [32]: arr
Out[32]: 
array([<pygeos.Geometry POINT (1 1)>, <pygeos.Geometry POINT (2 2)>,
       <pygeos.Geometry POINT (3 3)>], dtype=object)

In [33]: coords = pygeos.get_coordinates(arr) 

In [35]: new_coords = coords * 2 

In [36]: arr2 = pygeos.set_coordinates(arr, new_coords) 

In [37]: arr2  
Out[37]: 
array([<pygeos.Geometry POINT (2 2)>, <pygeos.Geometry POINT (4 4)>,
       <pygeos.Geometry POINT (6 6)>], dtype=object)

In [39]: arr  
Out[39]: 
array([<pygeos.Geometry POINT (2 2)>, <pygeos.Geometry POINT (4 4)>,
       <pygeos.Geometry POINT (6 6)>], dtype=object)
```

where the original array was modified in place.

**Comment by jorisvandenbossche** [comment]
@caspervdw actually, there is a comment in the code about this function being inplace:

https://github.com/pygeos/pygeos/blob/56ad4d09ae1fae1518dace7d8134c22a79e5c106/src/coords.c#L326-L330

And it is also purposefully assigning the new geometry to a pointer in the original array:

**Comment by jorisvandenbossche** [comment]
I think what makes this confusing / surprising, is: 1) I am not sure that in general you want to overwrite the existing geometries (eg in projections ("to_crs"), you might want to keep the original geometries), 2) the fact that it returns a "new" array (although this is identical (in python sense) to the passed one) also doesn't give the impression it is inplace

I think I would rather change the behaviour (although then you don't have the ability to do it inplace if you actually want), but I am also fine with keeping as is if there are good reasons for that, in which case I can do docstring update.

**Comment by caspervdw** [comment]
@jorisvandenbossche This also surprises me. But on second thought, I think this is good behaviour. I would like to leave it up to the user if he wants to copy the array. I really see these `get_coordinates` and `set_coordinates` as low-level functions.

Of course the docstrings are wrong. That the array is updated inplace should be documented (with a nice red 'warning' box).

A common usage would be `set_coordinates(arr.copy(), new_coords)`.

I'd prefer advertising the usage of the `apply` function (which purposefully makes a copy)

**Comment by jorisvandenbossche** [comment]
Yeah, the reason that I am using `get/set_coordinates` directly, is because pyproj.Transformer.transform needs two arrays and returns two arrays, not a single 2D array. But of course, I can also wrap it in a small function that does this, and then use `apply` instead.

I am fine with updating the docs.
