### ISSUE TITLE
CRS reprojection

### ISSUE THREAD

**Issue by ElcoK** [pygeos/pygeos#95]
Hi guys,

First of all, thanks for the great work here! 

I was browsing through the documentation in search of a function to reproject to a different coordinate system. One use case (for me) is to convert a linestring geometry from degrees to meters to get the actual length. 

Is this already implemented or potential work in progress?

Thanks!

Elco

**Comment by jorisvandenbossche** [comment]
Thanks for the interest!

This is already possible with the `get/set_coordinates` machinery (or wrapped with `apply`), in combination with pyproj to provide the actual transformation function, eg:

```
import pygeos
import pyproj

transformer = Transformer.from_crs("EPSG:4326", "EPSG:28992", always_xy=True)

coords = pygeos.get_coordinates(geometries)
new_coords = transformer.transform(coords[:, 0], coords[:, 1])
result = pygeos.set_coordinates(geometries.copy(), np.array(new_coords).T)
```

(you can also use `result = pygeos.apply(geometries, func)`, but then you need to wrap `transformer.transform` in another function that concatenates x/y arrays)


We should add this as an example to the docs.

(just added this to the GeoPandas branch that is integrating pygeos today: https://github.com/geopandas/geopandas/pull/1154/commits/1013ee8b09e056ddf1ea6239536a000483878ea0)
