### ISSUE TITLE
Distribute wheels on PyPI 

### ISSUE THREAD

**Issue by caspervdw** [pygeos/pygeos#98]
Maybe we could use this:
https://gertjanvandenburg.com/blog/wheels/

**Comment by mwtoews** [comment]
Windows is the tricky one. Over at Shapely I recently reworked an appveyor to compile/cache GEOS, then build and check the .whl files, which can be uploaded to PyPi. I'm not sure if it's the best solution, but it's what I was able to make work, as there is a big demand to install shapely on Windows via pip. If you're interested, I can rework a similar Windows setup for pygeos.

Sean also has [shapely-wheels](https://github.com/shapely/shapely-wheels) based on [multibuild](https://github.com/matthew-brett/multibuild) for Linux and MacOS (I think?).

Perhaps a workflow could be gathered into a new https://github.com/pygeos/pygeos-wheels repo.

**Comment by caspervdw** [comment]
Thanks for the offer on the appveyor part. I was thinking on just getting the GEOS binaries from https://trac.osgeo.org/osgeo4w/. Out of curiosity, why did you choose to compile it yourself? 

Anyway, I’d be happy if you want to port your windows build recipe to pygeos 👍

**Comment by mwtoews** [comment]
I chose to compile GEOS within Appveyor to have full control of the version of GEOS, and which compiler is used. For instance, CPython versions 3.5, 3.6, 3.7, 3.8 was compiled with Visual C++ 14.X ([see ref](https://wiki.python.org/moin/WindowsCompilers)), so I get to ensure that the same tools are used to compile objects intended to work with CPython. This is a bigger deal if/when a different version of Python is released that depends on a different Visual C++ version.

I suppose the other options are to use an upstream precompiled package, like vcpkg's [geos port](https://github.com/microsoft/vcpkg/tree/master/ports/geos), and cond's [geos](github.com/conda-forge/geos-feedstock). Perhaps these could work, I haven't checked. I'm always open to change the workflow, however.

**Comment by caspervdw** [comment]
I see. I think we should minimize ABI incompatibilities with the shapely wheels so I am :+1: in following the same approach

**Comment by caspervdw** [comment]
A work in progress on the manylinux part (based on https://github.com/shapely/shapely-wheels):

- https://github.com/pygeos/pygeos-wheels
- https://travis-ci.com/pygeos/pygeos-wheels

They still fail with `ImportError: No module named 'pygeos.lib'`

If anybody has an idea what I did wrong is not working, please tell me :)
I will try to find some time coming weeks to debug.

**Comment by caspervdw** [comment]
An update: the multibuild now passes (although the bug in #100 is blocking sometimes).
Now I need a place to put the artefacts.

I was thinking of making a 'production' branch (or 'pypi') and let Travis send the wheels to PyPI directly if the build is on that branch. Then (in the future) we will just need to bump the version number, make a PR to that branch, merge, and the CI's will publish the wheels automatically. More or less like it's done on conda-forge.

**Comment by caspervdw** [comment]
Closing this, thanks again @mwtoews for your contribution on the windows side
